import Link from 'next/link';
import GrowthSlideshow from '@/components/GrowthSlideshow';
import {Sprout,BookOpen,ChartNoAxesCombined,Compass,ArrowUpRight,ShieldCheck} from 'lucide-react';
const summary='Sprout is a learning platform for people who want to understand trading and personal finance, starting with the basics. Clear lessons, interactive quizzes, helpful planning tools, and a virtual trading simulator let you build skills at your own pace.';
const practice='Practice uses simulated prices and virtual money, so you can explore decisions without risking real funds.';
export default function About({embedded=false}:{embedded?:boolean}){
 if(embedded)return <section id="about" className="card dashboard-mission"><Sprout size={28}/><div><span className="eyebrow">LEARN. PRACTICE. GROW.</span><h2>About Sprout Trading</h2><p>{summary}</p><p>{practice}</p></div></section>;
 return <div className="about-page" id="about"><section className="about-hero"><div className="about-hero-copy"><span className="eyebrow">ABOUT SPROUT TRADING</span><h1>A clearer start.<br/><span>A stronger foundation.</span></h1><p>{summary}</p><div className="about-actions"><Link className="primary" href="/learn">Start learning <ArrowUpRight size={17}/></Link><Link className="secondary" href="/market">Try the simulator <ArrowUpRight size={17}/></Link></div></div><div className="about-growth" aria-hidden="true"><div className="about-growth-ring"/><div className="about-growth-mark"><Sprout size={100} strokeWidth={1.5}/></div><span className="about-growth-caption">Small steps. Lasting understanding.</span><span className="about-growth-tag"><ShieldCheck size={16}/> Virtual practice. Real learning.</span></div></section><GrowthSlideshow/><section className="card about-purpose"><span className="eyebrow">OUR MISSION</span><h2>Make understanding accessible.</h2><p>Trading and personal finance should feel approachable, even on day one. We make room to ask questions, understand possible losses, and build thoughtful habits at your own pace.</p></section><section className="about-pillars" aria-label="How Sprout helps you learn">{[{Icon:BookOpen,title:'Learn with clarity',text:'Short lessons and interactive quizzes turn unfamiliar ideas into something you can understand.'},{Icon:ChartNoAxesCombined,title:'Practice with purpose',text:'Explore charts, plan a virtual trade, and reflect on your decisions without risking real funds.'},{Icon:Compass,title:'Grow at your pace',text:'Use your learning progress and practice results to find your next useful step.'}].map(({Icon,title,text},i)=><article className="card about-pillar" key={title}><div className="about-pillar-top"><span className="module-icon"><Icon size={24}/></span><span className="eyebrow">0{i+1}</span></div><h2>{title}</h2><p>{text}</p></article>)}</section><div className="about-practice-note"><ShieldCheck size={20}/><p>{practice} There’s no universal amount needed to start learning.</p></div></div>;
}
