import Link from 'next/link';
import {ShieldCheck,FileText,CreditCard,LifeBuoy} from 'lucide-react';
export const policyPages=['privacy','terms','cancellation','support'];
export function PolicyLinks(){return <nav className="policy-links" aria-label="Legal and support">{policyPages.map(page=><Link key={page} href={`/${page}`}>{page==='cancellation'?'Cancellation':page[0].toUpperCase()+page.slice(1)}</Link>)}</nav>;}
const email=process.env.NEXT_PUBLIC_SUPPORT_EMAIL||'sprouttradinghelp@gmail.com';
const contact=<a href={`mailto:${email}`}>{email}</a>;
const sections:Record<string,[string,string][]>={
 privacy:[
 ['Information you provide','When you create an account, Sprout uses your email and authentication information. You may also provide a display name, handle, bio, country, timezone and profile picture. We store learning progress, quiz attempts, virtual trades, holdings, journal notes, mood check-ins, preferences and referral activity to operate the service.'],
 ['Browser storage','Guest progress, sign-in session information, theme preferences and activity measurements may be stored in your browser. Guest data is tied to that browser and can be lost when storage is cleared. Clearing browser data does not delete your cloud account.'],
 ['How information is used','We use account information to authenticate users, save progress, provide learning and simulator features, display community activity, administer referrals and subscriptions, and respond to support requests. Study and simulator time measurements support your personal learning insights.'],
 ['Community and profile visibility','Reviews, discussion posts and information you choose to share in community features may be visible to other users. Leaderboards may display your name or handle and virtual portfolio information. Do not post passwords, payment details or other sensitive information. Profile insight settings do not automatically make community posts private.'],
 ['Service providers','Supabase supports authentication and cloud account storage; Vercel hosts the website. Stripe handles billing when payments are enabled, including payment details and subscription records. Sprout does not receive your full card number. Embedded market widgets and external video or research links may connect to third-party services with their own privacy practices.'],
 ['Automated assistance','Sprouty provides automated educational help. If AI assistance is enabled, the question and recent conversation can be sent to OpenAI to generate a response, including web research. Do not enter confidential information. Library-based answers remain available when that integration is disabled.'],
 ['Retention and deletion','Cloud account information is generally retained while your account is active. Use Settings → Account & security → Delete account to request deletion through the available account controls. Linked subscriptions are canceled before account deletion. Some billing records, provider logs or backups may remain under provider retention rules or applicable legal obligations. Guest browser data is separate.'],
 ['Your choices','You can edit your profile, change supported notification and privacy preferences, and delete your account in Settings. Contact support for access, correction, export or deletion requests that the interface cannot complete. Rights depend on your location.'],
 ['Security and updates','We use authenticated access and access controls, but no service can guarantee absolute security. This notice may change as features or providers change; the effective date will be updated.'],
 ],
 terms:[
 ['Educational service','Sprout Trading is an educational platform and virtual trading simulator. It is not a broker, investment adviser or custodian. It does not execute real-market trades or hold customer investment funds. Lessons and automated responses are general education, not personalized financial advice.'],
 ['Prices and examples','Simulator prices and activity are generated practice data, not actual exchange quotes or volume. External market references may be delayed or unavailable. Example outcomes are illustrations, not verified customer profits, expected returns or guarantees. Trading real assets can cause substantial losses, including the full amount invested.'],
 ['Accounts and eligibility','Use accurate account information and keep your credentials secure. Paid accounts must be created by adults legally able to enter a subscription agreement in their jurisdiction. Do not share credentials, impersonate others or use someone else’s payment method without permission.'],
 ['Starter and Pro','Starter provides the free access described on the pricing page. Sprout Pro is advertised at $10 USD per month and renews monthly when live billing is available. Taxes or other applicable charges, if any, must be disclosed at checkout. The checkout amount and billing period govern your purchase. Features may evolve; current availability is shown in the interface.'],
 ['Virtual balances and rewards','Simulator cash, referral bonuses, badges and titles have no cash value and cannot be withdrawn or redeemed for real assets. Deposits and rewards are not trading profits. Referral eligibility and simulator reset or recharge rules are described in the app. Do not create fake accounts or manipulate rewards, rankings or practice records.'],
 ['Acceptable use and community','Do not post unlawful, abusive or misleading content, expose private information, spam users, interfere with the service or attempt unauthorized access. Only submit reviews reflecting your actual experience. You retain ownership of your content and permit Sprout to store and display it as needed to provide the features where you submit it.'],
 ['Availability and limitations','Features, generated data and automated responses may contain errors or be interrupted. Check important information independently. We do not promise profits, uninterrupted availability or specific learning outcomes. These terms do not exclude protections or remedies that applicable law makes non-waivable.'],
 ['Cancellation and account closure','You may stop future subscription renewals through the billing portal when enabled. Cancellation and refund information is on the Cancellation page. Account deletion is separate from routine cancellation and can remove saved progress. Access may be restricted for misuse or security reasons.'],
 ['Changes and questions','Material changes to subscription pricing or terms will be communicated before they apply when required. Contact support with questions about these terms. Sprout Trading is owned and operated by Ryan Assoku. Contact sprouttradinghelp@gmail.com with questions about the service or these terms.'],
 ],
 cancellation:[
 ['Cancel future renewals','Sign in to the account that purchased Pro. Open Sprout Pro / Pricing → Manage subscription. In the Stripe billing portal, choose your subscription and cancel it, then check the displayed end date and confirmation. This button appears for accounts with a linked billing subscription.'],
 ['Access after cancellation','Routine cancellation stops future renewals. Pro access continues through the paid period’s end, subject to the subscription status received from Stripe. After that, Starter limits apply. Cancel before your next renewal date to avoid another recurring charge.'],
 ['Refund requests','Canceling renewal does not automatically refund an earlier charge. For duplicate, mistaken or disputed charges, submit a billing support request with the account email, charge date and receipt reference. Never send full card details. Requests are reviewed individually; applicable statutory refund and consumer rights remain available.'],
 ['Deleting your account','Deleting an account is permanent and differs from canceling renewal. Settings → Account & security → Delete account cancels linked subscriptions before removing cloud account data. Export or save information you need first. Deletion does not automatically issue a refund.'],
 ['When billing is unavailable','Live payments are currently being prepared. Sandbox/test checkouts do not collect real money. If Manage subscription is unavailable or a cancellation attempt fails, contact support rather than assuming the renewal stopped. Keep your confirmation for your records.'],
 ],
 support:[
 ['Learning and simulator help','Use Sprouty’s chat bubble for automated explanations and navigation help. Learn includes glossary and lesson resources; the simulator has an interactive chart tour. Sprouty cannot access your payment account, cancel subscriptions or promise investment outcomes.'],
 ['Human support','Pro members can submit a priority support request from the pricing page. Requests are limited to three per hour. Human replies are not guaranteed around the clock and no fixed response time is promised. The automated assistant does not replace human billing or privacy support.'],
 ['What to include','Describe the issue, which page it occurred on, your device and browser, and any error message. For account or billing issues, include the account email and receipt reference through a private support channel. Never share passwords, authentication codes, API keys or full card numbers.'],
 ['Billing and privacy requests','For cancellations, start with the billing portal. For account deletion, start with Settings. Contact support when those controls fail or for refund, access, export, correction and privacy requests. Email sprouttradinghelp@gmail.com for human support, including requests from Starter users.'],
 ],
};
export default function Policies({page}:{page:string}){
 const title=page==='privacy'?'Privacy notice':page==='terms'?'Terms of use':page==='cancellation'?'Cancellation & billing':'Help & support';const Icon=page==='privacy'?ShieldCheck:page==='terms'?FileText:page==='cancellation'?CreditCard:LifeBuoy;
 return <div className="policy-page"><header className="policy-hero"><Icon size={32}/><span className="eyebrow">SPROUT TRADING</span><h1>{title}</h1><p>Clear information about your account, your choices and the service.</p><small>Effective October 8, 2026</small></header><PolicyLinks/><div className="policy-sections">{sections[page]?.map(([heading,body])=><section className="card" key={heading}><h2>{heading}</h2><p>{body}</p></section>)}</div><section className="card policy-contact"><h2>Contact</h2><p>Sprout Trading · Owned and operated by Ryan Assoku</p><p>{contact}</p><p><a href="tel:+19083421806">(908) 342-1806</a></p><div className="about-actions"><Link className="secondary" href="/settings">Account settings</Link><Link className="primary" href="/pricing">Billing & in-app support</Link></div></section></div>;
}
