import type { Lesson } from "@/types";
// IDs are append-only so existing local and cloud completion records remain valid.
const content = [
  [
    "What is day trading?",
    "Day trading means opening and closing a position during the same trading day. A position is the shares you currently own. Investing usually focuses on holding for longer and on a business's long-term prospects. Neither approach guarantees profit. Day trading demands time and can lead to rapid losses.",
    "Buy a stock at 10 a.m. Monday and sell it at 2 p.m. Monday: a day trade. Buy Monday and sell Friday: not a same-day trade.",
    "Start by understanding the activity, rather than assuming frequent trading is a shortcut to income.",
    "You buy Monday and sell Friday. Is this a same-day trade?",
    "No, it spans different trading days",
    "Yes, every stock purchase is a day trade",
    "Only if the sale earns a profit",
  ],
  [
    "How a trading day works",
    "For US stock exchanges, regular trading is generally 9:30 a.m. to 4 p.m. Eastern Time on trading days. Weekends, exchange holidays, and some early-close days change availability. Eastern Time changes with daylight saving. Extended-hours sessions depend on your broker and security and can have fewer participants and wider spreads.",
    "A US market opening at 9:30 a.m. Eastern is not 9:30 a.m. in every timezone. Check the exchange calendar and your broker before placing an order. Sprout's simulation is always available and does not enforce exchange hours.",
    "A market being closed or thinly traded affects when and how an order can execute.",
    "Is the regular US stock market open every day?",
    "No; weekends, holidays, and schedules matter",
    "Yes, all markets trade continuously",
    "Yes, unless your browser is closed",
  ],
  [
    "Reading a stock quote",
    "A ticker is a short identifier such as AAPL. The last price is the most recent reported trade. The bid is a displayed buying offer; the ask is a displayed selling offer. Their difference is the spread. A timestamp tells you when the data was recorded; delayed or stale quotes may not reflect current conditions.",
    "Last $100, bid $99.90, ask $100.10: the spread is $0.20. A market buy might execute near the ask, not at the last price. Sprout displays generated quotes, not a live bid/ask feed.",
    "Know what a number represents before treating it as an available execution price.",
    "Does the last traded price guarantee your order's price?",
    "No; execution prices can differ",
    "Yes, every order uses the last price",
    "Only a stock's ticker determines the fill",
  ],
  [
    "What happens when you place an order?",
    "Submitted means your request has been sent, not completed. An accepted order can remain pending, fill partly, or fill completely. Rejected orders do not execute. A cancellation request can arrive too late: verify the final order status. A fill is the actual exchange of shares and cash.",
    "You request 10 shares. Four fill while six remain pending: you own four new shares, not ten. Sprout uses immediate whole-order market fills and simplified pending limit orders; it does not model partial fills.",
    "Check fills and remaining quantities before placing another order or assuming you own shares.",
    "Does submitting an order mean you own all the requested shares?",
    "No; you need to check what actually filled",
    "Yes, submission and execution are identical",
    "Yes, even if the order is rejected",
  ],
  [
    "Spreads, fees, and slippage",
    "The spread is the gap between bid and ask. Fees can include broker, exchange, regulatory, financing, or currency costs. Slippage is the difference between the price you expected and the price you actually received. Commission-free does not mean cost-free.",
    "Buy 10 shares at an ask of $100.10 and immediately sell at a bid of $99.90: that is a $2 loss before other costs. Sprout currently omits spreads, fees, and slippage from trade execution.",
    "Small costs repeated across frequent trades can meaningfully change the result.",
    "Can a commission-free trade still have costs?",
    "Yes; spreads, slippage, and other charges can matter",
    "No; it always has zero total cost",
    "Only losing trades incur costs",
  ],
  [
    "Liquidity and volatility",
    "Liquidity describes how easily an asset can be traded near available prices. Volatility describes how much prices fluctuate. A volatile asset can also be illiquid. Order size matters: a displayed price may only be available for a limited quantity.",
    "A stock moves quickly but few shares are offered. A large market order may fill at several different prices. Fast movement does not make execution easy.",
    "Assess both price movement and the ability to enter and exit, rather than treating excitement as opportunity.",
    "Does a fast-moving stock necessarily make an easy trade?",
    "No; volatility and liquidity are different",
    "Yes; movement guarantees easy execution",
    "Yes; a chart replaces the need to check liquidity",
  ],
  [
    "How much could you lose?",
    "For a long stock position, a price decline reduces its value. Multiply the price change per share by the number of shares to calculate a simple dollar loss. Position size controls how strongly a move affects your account. A planned exit does not cap the possible loss if execution differs.",
    "Ten shares bought at $100 and later valued at $95 lose $50 before costs. In a $10,000 account that is 0.5%. One hundred shares experiencing the same move lose $500.",
    "Translate percentages into dollars and account impact before considering a trade. Money needed for essential expenses should not be put at trading risk.",
    "Ten shares fall from $100 to $95. What is the loss before costs?",
    "$50",
    "$5",
    "$500",
  ],
  [
    "Stops and price gaps",
    "A stop-market order becomes a market order after its trigger condition is met. Its fill can be worse than the stop price. A stop-limit order instead becomes a limit order and might never fill. A price gap skips intermediate prices, such as after news or an overnight move.",
    "You buy at $100 and place a $95 stop. The next available price is $90: an exit at $90 loses $10 per share, not $5. Sprout teaches stops but does not execute stop orders.",
    "A stop can be part of a plan; it is not a guarantee of a maximum loss.",
    "Can a stock move past your stop price before you can exit?",
    "Yes; a gap can cause a worse fill",
    "No; every stop guarantees its price",
    "No; prices must trade at every cent",
  ],
  [
    "Cash accounts and margin accounts",
    "A cash account pays for purchases using the account's funds. A margin account can allow borrowing against eligible holdings, subject to broker and regulatory conditions. Borrowing can involve interest, forced sales, and losses beyond your initial deposit. Account restrictions differ by country, broker, product, and account type.",
    "A broker showing buying power does not mean all of that amount is your own cash or appropriate to use. Before live trading, check settled funds, borrowing terms, and current day-trading restrictions with your broker. Sprout does not lend money or model broker restrictions.",
    "Treat account rules as requirements to verify, not rules that a simulator automatically demonstrates.",
    "Does a broker's buying-power figure always represent your own available cash?",
    "No; it can include borrowing or account-specific limits",
    "Yes; borrowing is impossible",
    "Yes; all account types have identical rules",
  ],
  [
    "Settlement and available funds",
    "Execution and settlement are different. Execution is the trade; settlement is the completion of the securities and cash exchange. Many US stock trades settle on the next business day, commonly described as T+1, but products and jurisdictions differ. Cash-account trading with unsettled proceeds can create restrictions if the resulting purchase is sold before it has been paid for with settled funds.",
    "A typical US stock sale on Friday may settle Monday if it is a business day, rather than Saturday. Check your broker's settled-cash balance and policies. Sprout makes simulated sale proceeds immediately reusable and does not model settlement.",
    "Do not assume a simulator's instantly available cash reproduces live-account funding rules.",
    "Does selling a stock always make its proceeds immediately settled?",
    "No; check settlement and your account's rules",
    "Yes; execution and settlement are identical",
    "Yes; weekends count as regular settlement days",
  ],
  [
    "Making a trade plan",
    "Write down what you are observing, why you would enter, what would invalidate the idea, your intended exit conditions, and position size. Consider possible dollar loss and what happens if the exit price is worse than expected. Choosing not to trade is a valid decision.",
    "Example practice plan: observe a stock; buy only if a chosen condition occurs; use 5 virtual shares; reassess if the idea fails; record possible losses at several prices. This is an exercise, not a recommended strategy.",
    "Deciding before entering can reduce impulsive changes under pressure.",
    "When should you decide your entry reason, exit conditions, and position size?",
    "Before entering the trade",
    "Only after a loss",
    "Only if the price begins to rise",
  ],
  [
    "Trading emotions: FOMO and revenge trading",
    "FOMO means fear of missing out. Chasing a rapidly rising price can replace a plan with urgency. Revenge trading means taking new risks mainly to recover a loss. Fatigue and frustration can affect judgment. A pause, a written plan, and a predefined stopping rule can help you recognize impulsive decisions.",
    "After losing $50, doubling the next position just to win it back increases exposure; it does not erase uncertainty. Pause and review rather than treating the next trade as a debt the market owes you.",
    "You control whether to participate and how much exposure to take, not the market's next move.",
    "After a loss, should you increase your next trade just to win it back?",
    "No; pause and follow a considered plan",
    "Yes; a larger trade guarantees recovery",
    "Yes; the next trade must reverse the last result",
  ],
  [
    "Reviewing a trade: process versus luck",
    "Record your reason, planned conditions, size, actual fills, costs, outcome, and what you learned. Compare what you did with what you planned. A profitable trade can involve poor decisions; a losing trade can follow a reasonable plan. One outcome does not establish a reliable strategy.",
    "An impulsive trade earns $20. A planned trade loses $10. Profit alone does not tell you which process was better or what will happen next. Review many observations, including losses and skipped trades.",
    "Measure decision quality and consistency as well as money gained or lost.",
    "Does a profitable trade prove your strategy works?",
    "No; one outcome can reflect luck",
    "Yes; one win proves repeatability",
    "Yes; losses can now be ignored",
  ],
  [
    "What practice cannot teach you",
    "Sprout uses generated prices, simplified fills, and virtual cash. Real trading adds changing liquidity, slippage, costs, outages, account rules, and the emotional pressure of real losses. A simulated win is not evidence that a method will succeed with real money.",
    "A virtual order fills at a displayed quote immediately. In a real market it could fill later, partly, at another price, or not at all. A smooth simulated experience does not demonstrate live execution quality.",
    "Use practice to learn concepts and develop a review process, not as certification that you are ready for live trading.",
    "Do simulated profits prove you are ready to trade real money?",
    "No; simulation leaves out important real-world risks",
    "Yes; virtual fills predict live fills",
    "Yes; a winning screenshot is enough",
  ],
  [
    "News and earnings",
    "Earnings reports describe a company's financial performance. Prices react to expectations as well as the reported numbers. Unexpected announcements and economic news can change prices rapidly, including outside regular hours. A headline may be incomplete, outdated, or misunderstood.",
    "A company reports higher revenue, but its price falls because investors expected even more or its outlook weakened. Good-sounding news does not guarantee a price rise.",
    "Check the source, timing, and context instead of assuming a headline tells you the next move. Sprout does not simulate a news feed or earnings reactions.",
    "Can a stock fall after apparently positive earnings news?",
    "Yes; expectations and outlook also matter",
    "No; higher revenue guarantees a rise",
    "Only if the ticker changes",
  ],
  [
    "Trading halts and outages",
    "An exchange can temporarily halt trading, for example around significant news or extreme price movement. A broker, network, or platform can also become unavailable. Orders and cancellation requests may not execute when you expect; prices can change before trading resumes.",
    "A stock is halted while you hold it. You cannot assume you can sell immediately at the last quote. Check official notices and your broker's order status. Sprout does not simulate exchange halts.",
    "An exit plan must acknowledge that immediate execution is not always available.",
    "During a trading halt, can you assume an immediate exit at the last displayed price?",
    "No; trading and execution may be unavailable",
    "Yes; the last quote guarantees a buyer",
    "Yes; refreshing the page removes the halt",
  ],
  [
    "Leverage and short selling",
    "Leverage uses borrowing or instruments to increase exposure relative to your own funds. It amplifies losses as well as gains. Short selling typically involves borrowing shares and selling them, hoping to buy them back for less. A short can lose more than the initial amount because prices can keep rising; borrowing costs and forced closures may apply.",
    "A $2,000 position funded partly by $1,000 of your own money loses $200 on a 10% fall: 20% of your original $1,000 before costs. Shorting one share at $100 and buying it back at $150 loses $50 before costs. Sprout supports neither margin borrowing nor short selling.",
    "Learn these mechanisms without assuming that extra exposure is appropriate for a beginner.",
    "What can leverage do to your losses relative to your own funds?",
    "Amplify them, potentially beyond your initial deposit",
    "Guarantee they stay smaller",
    "Eliminate them when the chart looks favorable",
  ],
  [
    "Taxes and recordkeeping",
    "Real trades may create tax obligations even when proceeds stay in a brokerage account. Treatment depends on jurisdiction, account type, holding period, and individual circumstances. In the US, wash-sale rules can affect deductions for certain losses when substantially identical securities are repurchased within specified periods. Keep complete records and consult current official guidance or a qualified tax professional.",
    "Keep dates, securities, quantities, proceeds, costs, fees, and broker documents, rather than only a screenshot of total profit. Sprout's virtual trades are educational records, not real taxable securities transactions or tax reports.",
    "Frequent trading can make recordkeeping and tax questions more complicated; a simulator does not calculate your tax obligations.",
    "Are a profit screenshot and account balance a complete tax record?",
    "No; keep transaction records and applicable documents",
    "Yes; individual transactions never matter",
    "Yes; taxes only matter when cash leaves the broker",
  ],
  [
    "Misleading trading claims and scams",
    "Be skeptical of guaranteed returns, pressure to act quickly, promises of easy daily income, and requests to send money to unverified people. Screenshots can be fabricated or omit losses and costs. An influencer's confidence or large following does not establish expertise or suitable advice.",
    "A post shows one winning trade and sells a guaranteed-profit course. You cannot infer a complete track record or future reliability from that screenshot. Verify identities and information through independent, reliable sources.",
    "Protect your money and account credentials; education should help you question claims, not chase promises.",
    "Which claim is a warning sign?",
    "Guaranteed daily profits with no risk",
    "A clear explanation of possible losses",
    "A transparent description of simulation limits",
  ],
  [
    "Practice: read a quote",
    "Use the practice quote below to identify the ticker, last price, bid, ask, spread, and timestamp. These values are fixed educational examples, not executable prices or a live feed.",
    "PRACT: last $100.00, bid $99.90, ask $100.10, recorded at 10:00 a.m. Eastern. The spread is ask minus bid. A last price does not guarantee a market fill.",
    "Learn to distinguish the fields before deciding what an order might cost.",
    "What is the spread in this practice quote?",
    "$0.20",
    "$100.00",
    "$0.10",
  ],
  [
    "Practice: calculate a possible loss",
    "Use the share-count control below. A decline from $100 to $95 loses $5 per share before costs. Notice how changing shares changes both the dollars at risk and the impact on a $10,000 example account. This is a scenario, not a promised maximum loss.",
    "Five shares lose $25, ten lose $50, and twenty lose $100 on that same $5 decline. A larger decline would lose more.",
    "Make position size a deliberate decision based on possible outcomes rather than excitement.",
    "How much do 20 shares lose on a $5-per-share decline before costs?",
    "$100",
    "$5",
    "$20",
  ],
  [
    "Practice: choose an order",
    "A market order prioritizes execution, with uncertain price. A buy limit sets a maximum purchase price but might not fill. Use the comparison below to consider the tradeoff; no order type guarantees both a chosen price and immediate execution.",
    "A simulated ask is $100.10. If you are only willing to pay $100, a $100 buy limit expresses that maximum; it does not guarantee that a seller will accept it.",
    "Choose the order condition that matches your intended decision rather than assuming every order behaves the same way.",
    "Which order expresses a maximum buy price of $100?",
    "A buy limit at $100, which may not fill",
    "A market order guaranteed to fill at $100",
    "Any order; all types guarantee $100",
  ],
  [
    "Practice: write a trade plan",
    "Fill in the example plan below: observation and entry condition, what would invalidate the idea, intended exit conditions, and number of virtual shares. Estimate a loss scenario before considering an order. The worksheet does not place a trade or create a stop order.",
    "Example: 5 virtual shares at $100; evaluate an exit near $95 if the idea fails. That scenario loses $25 before costs, but gaps or worse fills could lose more. A plan can also say 'skip the trade.'",
    "Practice naming both a reason to enter and a reason to stop participating.",
    "Does writing an intended exit at $95 guarantee a $95 sale?",
    "No; execution can differ and the worksheet places no order",
    "Yes; a written plan creates a guaranteed stop",
    "Yes; planning eliminates possible loss",
  ],
  [
    "Practice: review an outcome",
    "Compare two example trades using both process and result. Describe what matched the plan, what changed, and what you would review. Avoid judging a strategy from one win or one loss.",
    "Trade A followed its written size and exit plan and lost $10. Trade B doubled size impulsively and made $20. Trade B's profit does not prove that abandoning a plan was a good decision.",
    "A useful review identifies behavior you can improve and uncertainty you cannot remove.",
    "Which statement is supported by these examples?",
    "A profitable result alone does not prove a good process",
    "Trade B proves impulsive sizing always works",
    "Trade A proves planning never helps",
  ],
];
export const dayTradingLessons: Lesson[] = content.map((c, index) => ({
  id: 31 + index,
  level: index < 5 ? 7 : index < 10 ? 8 : index < 14 ? 9 : index < 19 ? 10 : 11,
  title: c[0],
  explanation: c[1],
  example: c[2],
  why: c[3],
  quiz: {
    question: c[4],
    options: [c[6], c[5], c[7]],
    answer: 1,
    explanation: c[2] + " " + c[3],
  },
}));
export const beginnerLearningOrder = [
  31, 1, 3, 4, 5, 32, 33, 9, 34, 11, 12, 35, 36, 37, 14, 15, 38, 13, 39, 40, 41,
  42, 43, 44, 2, 6, 7, 8, 10, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 16, 17,
  18, 19, 20, 26, 27, 28, 29, 30, 21, 22, 23, 24, 25,
];
export const accountRulesMetadata = {
  updated: "2026-10-06",
  scope:
    "US stock examples. Rules vary by country, broker, product, and account type. Verify current requirements before live trading.",
  sources: [
    {
      label: "NYSE hours and calendars",
      url: "https://www.nyse.com/markets/hours-calendars",
    },
    {
      label: "FINRA investor guidance",
      url: "https://www.finra.org/investors",
    },
    { label: "SEC investor education", url: "https://www.investor.gov/" },
    {
      label: "IRS investment income guidance",
      url: "https://www.irs.gov/publications/p550",
    },
  ],
};
