export const glossary=[
 ['VWAP','Volume-weighted average price: the average price paid during a period, weighted by shares traded.','100 shares at $10 and 300 at $12 produce VWAP $11.50.',57],
 ['Pullback','A temporary move against an existing trend. It may develop into a reversal.','Price rises 95 → 101, then falls to 99. The dip is a pullback until the broader trend changes.',113],
 ['Liquidity','How readily an asset can be traded without substantially moving its price.','A narrow spread and many available orders may help execution, but can change quickly.',36],
 ['Bullish','Expecting prices to rise over a stated timeframe; not a guarantee.','A trader may be bullish over months while expecting a short-term decline.',144],
 ['Bearish','Expecting prices to fall over a stated timeframe.','A bearish view needs evidence and a timeframe, not just a red candle.',144],
 ['Spread','The difference between the best quoted ask and bid.','Ask $100.10 minus bid $99.90 = $0.20 spread.',35],
 ['Stop loss','An order intended to exit after a price trigger. Execution and price are not guaranteed.','A gap below a $95 stop may result in a fill below $95.',13],
 ['Position size','The number of shares or units held in a trade.','A $50 planned risk divided by a $2 entry-to-stop distance gives 25 shares before costs.',14],
 ['Resistance','An observed price area where selling previously slowed a rise. It can break.','Several reactions around $110 suggest an area to watch, not a ceiling.',20],
 ['Support','An observed price area where buying previously slowed a decline. It can break.','Previous bounces near $100 do not guarantee the next bounce.',20],
 ['Volume','The number of shares or units traded during a period.','A busier session has more transactions; volume alone does not tell you the next direction.',10],
 ['ETF','An exchange-traded fund: a basket of investments traded in shares.','A broad stock ETF may hold many businesses, while a sector ETF may be concentrated.',77],
 ['Diversification','Spreading exposure across investments whose risks are not identical.','Two funds holding the same companies can overlap heavily.',80],
 ['FOMO','Fear of missing out: pressure to act because others appear to be benefiting.','Chasing a rapid rise without a plan is a common FOMO response.',42],
 ['Drawdown','The fall from a portfolio’s previous peak to a later lower value.','A fall from $10,000 to $9,000 is a 10% drawdown.',123],
 ['R multiple','A trade result divided by its planned initial risk.','A $100 gain on $50 planned risk is +2R before costs.',138],
 ['Market order','An order seeking prompt execution at available prices.','Your fill may differ from the displayed quote.',11],
 ['Limit order','An order specifying the maximum buy or minimum sell price; it may not fill.','A $100 buy limit can fill at $100 or less, if execution is available.',12],
 ['Candlestick','A chart mark showing a period’s open, high, low, and close.','A green body can mean close above open, but does not promise another increase.',18],
 ['Compound interest','Interest or returns that themselves can earn interest or returns.','At a hypothetical fixed 5%, $1,000 grows to $1,050 then $1,102.50. Market returns are not fixed.',73],
 ["Stock", "An ownership interest in a company, divided into shares.", "Owning one share gives a small stake; it does not guarantee a profit.", 1],
 ["Share", "One unit of ownership in a company or fund.", "Buying three shares at $20 costs $60 before fees.", 3],
 ["Ticker symbol", "A short code used to identify a traded security.", "AAPL identifies Apple stock; check the company and exchange too.", 33],
 ["Exchange", "A marketplace with rules for trading listed securities.", "The NYSE and Nasdaq are US stock exchanges.", 32],
 ["Broker", "A firm that provides access to investment accounts and order execution.", "A broker routes an order; it does not guarantee a profitable trade.", 34],
 ["Portfolio", "The collection of investments and cash you hold.", "Cash, shares of two companies, and an ETF can all be in one portfolio.", 24],
 ["Bid", "The highest currently quoted price a buyer offers for a security.", "A $99.90 bid is an offer to buy, not the price you necessarily pay to buy.", 9],
 ["Ask", "The lowest currently quoted price a seller asks for a security.", "With a $100.10 ask, an available seller is offering shares at that price.", 9],
 ["Slippage", "The difference between an expected execution price and the actual fill.", "An expected $100 purchase fills at $100.20, costing $0.20 more per share.", 35],
 ["Fill", "Execution of all or part of an order.", "An order for ten shares may fill only four initially.", 34],
 ["Partial fill", "Execution of only some of the quantity requested.", "Four shares fill from a ten-share order; six remain unfilled.", 102],
 ["Stop-limit order", "An order that becomes a limit order after its stop trigger is reached. It may not execute.", "A triggered sell limit can remain unfilled if the market moves below its limit.", 38],
 ["Price gap", "A jump between traded prices with no trades at the intermediate prices.", "A stock closes at $100 and next trades at $94 after news.", 38],
 ["Trading halt", "A temporary pause in trading a security under applicable market rules.", "A halt can prevent an exit until trading resumes.", 46],
 ["Settlement", "Completion of the exchange of cash and securities after a trade.", "A trade executes today, but settlement follows the applicable account and market schedule.", 40],
 ["Cash account", "A brokerage account that pays for investments without borrowing on margin.", "Available cash and settled funds can differ; account rules still apply.", 39],
 ["Margin account", "A brokerage account that may allow borrowing against eligible holdings.", "Borrowing can increase exposure and create interest costs and margin calls.", 39],
 ["Margin call", "A demand to restore required equity in a margin account; positions may be liquidated.", "Falling collateral value can lead a broker to require funds or sell holdings.", 120],
 ["Leverage", "Exposure larger than the capital committed, often through borrowing or derivatives.", "A 10% move on twice your capital produces a larger account change before costs.", 120],
 ["Long position", "A position that generally benefits when the asset price rises.", "Buying five shares creates a long stock position.", 3],
 ["Short selling", "Selling borrowed securities with an obligation to return equivalent securities.", "Selling borrowed shares at $100 and buying back at $110 creates a loss before costs.", 121],
 ["Unrealized gain or loss", "A change in value on an investment you still hold.", "A share bought at $100 and currently valued at $110 has a $10 unrealized gain.", 5],
 ["Realized gain or loss", "A gain or loss recognized when an investment is sold or otherwise disposed of.", "Selling a $100 share for $90 realizes a $10 loss before costs.", 84],
 ["Cost basis", "The amount used to determine a taxable gain or loss, including applicable adjustments.", "A $100 purchase plus certain costs can produce a basis different from the quoted share price.", 87],
 ["Capital gain", "A gain from disposing of a capital asset for more than its adjusted basis.", "Selling for $120 with a $100 basis creates a $20 gain before other adjustments.", 85],
 ["Dividend", "A distribution a company pays to shareholders, often in cash. It is not guaranteed.", "A $1 dividend on each of ten shares pays $10 before taxes.", 78],
 ["Market capitalization", "Share price multiplied by the number of outstanding shares.", "One million shares at $10 imply a $10 million market capitalization.", 7],
 ["P/E ratio", "Price-to-earnings ratio: share price divided by the chosen earnings per share measure.", "A $50 price and $5 earnings per share give a P/E of 10; context still matters.", 106],
 ["Revenue", "Money a business earns from selling goods or services before subtracting expenses.", "A company can report $1 million in revenue and still lose money.", 104],
 ["Net income", "Profit or loss after the expenses and taxes included in an accounting period.", "Revenue of $100 minus total accounting expenses of $90 gives $10 net income.", 104],
 ["Cash flow", "Cash moving into or out of a business or household.", "A company can report profit while customers have not yet paid their invoices.", 105],
 ["Earnings report", "A company update on financial results for a reporting period.", "Reported profit may rise while the share price falls if investors expected more.", 107],
 ["Balance sheet", "A statement of assets, liabilities, and equity at a particular date.", "Cash and equipment are assets; outstanding loans are liabilities.", 104],
 ["SEC filing", "A disclosure submitted under US securities reporting rules.", "Research a company’s public annual report through SEC EDGAR.", 140],
 ["Form 4", "A US filing reporting certain changes in insiders’ beneficial ownership.", "Check transaction codes, dates, and notes before calling a change a market purchase.", 149],
 ["Insider transaction", "A securities transaction involving a company insider that may be subject to disclosure rules.", "Shares received as compensation are different from an open-market purchase.", 150],
 ["Bull market", "A period broadly characterized by rising prices; definitions and timeframes vary.", "A rising broad market can still contain falling stocks and temporary declines.", 144],
 ["Bear market", "A period broadly characterized by falling prices; definitions and timeframes vary.", "A falling broad market can have sharp temporary rallies.", 144],
 ["Trend", "The general direction of price movement over a chosen timeframe.", "Higher highs and higher lows may describe an uptrend on that chart.", 19],
 ["Breakout", "A move beyond an observed trading range or price area. It may fail.", "Price moves above resistance near $110; later behavior still matters.", 112],
 ["Failed breakout", "A move beyond an observed level that subsequently returns inside the previous area.", "Price briefly crosses $110, then returns below it.", 112],
 ["Reversal", "A change in the direction of an established trend.", "A rising trend may shift into lower highs and lower lows; confirmation depends on context.", 113],
 ["Trading range", "An interval in which prices repeatedly move between observed upper and lower areas.", "Several sessions oscillate between approximately $95 and $105.", 114],
 ["OHLC", "Open, high, low, and close: four prices describing a chart period.", "A candle opens at $100, reaches $105 and $98, and closes at $103.", 18],
 ["Candle wick", "The thin part of a candlestick extending to a period’s high or low.", "A long lower wick shows prices recovered from the period’s low, not a certain future rise.", 26],
 ["Candle body", "The part of a candlestick between its opening and closing prices.", "An open at $100 and close at $103 create a $3 body.", 26],
 ["Doji", "A candle with an opening and closing price close together relative to its range.", "An open at $100 and close at $100.05 can form a small body; context matters.", 28],
 ["Hammer", "A candle shape with a small body near the top and a long lower wick.", "After a decline, it can show intraperiod recovery without guaranteeing a rebound.", 29],
 ["Engulfing pattern", "Two candles where the later body covers the earlier body in the opposite direction.", "A falling $105-to-$100 body is followed by a rising $98-to-$107 body.", 30],
 ["Moving average", "An average of prices over a selected number of periods, updated as new data arrives.", "Five closes of $10, $11, $12, $11, and $11 have an average of $11.", 55],
 ["RSI", "Relative Strength Index: a momentum measure comparing recent gains with losses.", "An RSI above 70 can persist in a strong trend; it does not guarantee a fall.", 56],
 ["ATR", "Average True Range: a measure of price-movement size that accounts for gaps.", "A larger ATR suggests bigger recent ranges, not a particular price direction.", 58],
 ["Asset allocation", "How a portfolio is divided among asset types.", "A portfolio might divide money among stocks, bonds, and cash.", 81],
 ["Correlation", "A measure of how two sets of returns move together over a chosen period.", "Two funds owning similar businesses may fall together even with different names.", 80],
 ["Rebalancing", "Adjusting holdings to bring a portfolio back toward a planned allocation.", "Stock gains change a 60% stock target to 70%; rebalancing can restore the target.", 82],
 ["Risk/reward ratio", "A comparison of planned potential loss with a hypothetical potential gain.", "A $10 planned loss and $20 target gain give a 1:2 risk/reward ratio; neither fill is guaranteed.", 22],
 ["Win rate", "The share of eligible recorded trades that produced a gain, using a stated counting method.", "Four winning trades out of ten eligible trades give 40%; that alone does not prove profitability.", 138],
 ["Budget", "A plan for how available income will cover spending, saving, and other goals.", "A $2,000 income with $1,500 spending leaves $500 to allocate.", 66],
 ["Net worth", "The value of what you own minus what you owe.", "Assets of $5,000 minus debts of $1,500 give $3,500 net worth.", 61],
 ["Asset", "Something you own that has financial value.", "Cash, investments, and property can be assets; access and value can vary.", 61],
 ["Liability", "A financial obligation or debt you owe.", "An outstanding loan balance is a liability.", 61],
 ["Interest", "The cost of borrowing money or an amount earned on eligible savings or lending.", "At a simple 5% yearly rate, $100 earns $5 over one year before other effects.", 70],
 ["APR", "Annual percentage rate: a yearly borrowing-cost measure, with included costs depending on the product.", "Compare APR, fees, and repayment terms rather than just the advertised payment.", 70],
 ["APY", "Annual percentage yield: an annualized deposit return that includes compounding under stated assumptions.", "A quoted APY assumes particular compounding and rate conditions; rates can change.", 70],
 ["Inflation", "A rise in the general price level that reduces money’s purchasing power.", "If a basket rises from $100 to $103, buying it requires 3% more money.", 71],
 ["Emergency fund", "Accessible money set aside for unexpected essential expenses or income disruption.", "A repair or interrupted paycheck may require cash before an investment can be sold.", 68],
 ["Sinking fund", "Money saved gradually for a known future expense.", "Saving $50 a month for a $600 annual bill prepares for that cost.", 67],
 ["Credit utilization", "The proportion of available revolving credit currently used, as reported.", "A $200 balance against a $1,000 limit is 20% utilization.", 75],
 ["Index fund", "A fund designed to track a stated index, subject to fees and tracking differences.", "A fund may aim to follow a broad stock index; its price can still fall.", 77],
 ["Bond", "A debt security with terms for payments and repayment, subject to issuer and market risk.", "A bond issuer owes contractual payments; default or rate changes can affect value.", 76],
 ["Dollar-cost averaging", "Investing a planned amount at regular intervals regardless of price. It does not guarantee gains.", "A monthly contribution buys more shares when prices are lower and fewer when higher.", 83],
 ["IRA", "An individual retirement account subject to eligibility, contribution, and withdrawal rules.", "An IRA is an account structure, not a single investment.", 90],
 ["Roth account", "An account structure generally funded with after-tax contributions, with tax treatment depending on the rules.", "Qualified withdrawals can be tax-free, but eligibility and conditions still matter.", 89],
 ["401(k)", "A US employer-sponsored retirement plan with contribution and withdrawal rules.", "An employer may match some employee contributions, subject to plan terms.", 88],
 ["Deductible", "An amount you pay toward covered costs before specified insurance benefits apply.", "With a $500 deductible, you may bear the first $500 of an eligible claim under the policy.", 92],
 ["Wash sale", "A US tax rule that can defer certain losses when substantially identical securities are bought within the relevant window.", "Buying back a substantially identical security soon after a loss sale can change tax treatment.", 86],
 ["Opportunity cost", "The benefit of the next-best alternative you give up when making a choice.", "Time spent trading cannot also be spent working or studying something else.", 63],
 ["Expense ratio", "A fund’s recurring operating expenses expressed as a percentage of fund assets.", "A 0.20% ratio corresponds to about $2 yearly per $1,000 if value stays constant.", 77],
 ["Purchasing power", "The goods or services an amount of money can buy.", "If prices rise while savings stay unchanged, the same dollars buy less.", 71],
 ["Trading plan", "Written rules for when to enter, when to exit, and how much to risk.", "A plan states the setup, size, invalidation point, and reasons to skip.", 41],
] as const;
export const mistakes=[
 {name:'Overtrading',problem:'Repeated trades without a fresh reason can increase costs and poor decisions.',fix:'Write an entry condition and a session trade limit. Stopping is a valid choice.',scenario:'You have already taken your planned three trades. A fourth setup is unclear. What now?',options:['Keep trading until you make more','Pause and review your plan'],answer:1,lesson:45,prices:[100,101,99,102,100,101,99]},
 {name:'Entering too late',problem:'Chasing a move can leave a large potential loss compared with the remaining opportunity.',fix:'Recheck entry, invalidation, and size. Skip if the original plan no longer fits.',scenario:'Price has run far beyond your planned entry. Which choice fits a disciplined process?',options:['Reassess the plan and consider skipping','Buy more so you do not miss out'],answer:0,lesson:137,prices:[95,96,98,99,103,108,111]},
 {name:'No exit or risk plan',problem:'A position without a defined loss limit can become an uncontrolled bet.',fix:'Choose a practical invalidation point and affordable size. Stops can slip or gap.',scenario:'You cannot explain how much a trade could lose. What comes first?',options:['Enter and figure it out later','Define risk before entering'],answer:1,lesson:40,prices:[105,104,102,99,97,94,91]},
 {name:'Revenge trading',problem:'Trying to immediately recover a loss can turn frustration into oversized risk.',fix:'Take a break, record the emotion, and review the next decision separately.',scenario:'You lost a trade and want to double the next position to recover. What helps?',options:['Pause, journal, and return to your normal risk plan','Double down before you calm down'],answer:0,lesson:45,prices:[100,102,99,96,98,94,93]},
 {name:'FOMO entries',problem:'A fast move or social post can create urgency without a researched reason.',fix:'Separate evidence from excitement. No trade is better than an unplanned trade.',scenario:'A post promises a stock will soar. You have not researched it. What do you do?',options:['Buy immediately because everyone is excited','Check reliable sources and define a plan first'],answer:1,lesson:142,prices:[98,99,100,104,109,105,100]},
];
export function dailyWarmupIndex(date:Date){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);const value=(type:string)=>parts.find(p=>p.type===type)!.value;return Math.floor(Date.UTC(Number(value('year')),Number(value('month'))-1,Number(value('day')))/86400000)%3;}
export const warmups=[
 {title:'A pullback within a rising trend',prices:[95,97,96,99,98,102,100],level:100,annotation:'Recent pullback',why:'A dip can offer a place to reassess a trend, but can also become a reversal.',look:'Compare the bigger trend, a possible invalidation point, and affordable risk.',lesson:145},
 {title:'Resistance and a possible breakout',prices:[98,100,99,102,101,104,105],level:104,annotation:'Observed resistance',why:'An observed level helps organize a question. Moving above it does not prove the breakout will last.',look:'Watch for follow-through and failed moves. Plan what would change your view.',lesson:147},
 {title:'Support under pressure',prices:[106,104,102,100,103,101,99],level:100,annotation:'Observed support',why:'Repeated reactions make an area interesting, but support can fail.',look:'Ask whether the previous observation still holds. Waiting is an option.',lesson:146},
];
