import type {Lesson} from '@/types';
const content = [
 ['Moving averages: smoothing the noise','A moving average shows the average closing price over a chosen number of periods. A 5-period simple moving average adds the last five closes and divides by five. It smooths noise but reacts after prices move. A rising average does not guarantee the next price will rise.','Closes of $10, $11, $12, $11, $11 have an average of $11. Longer averages react more slowly.','Use an average to describe a trend, then consider price, context, and risk.','What does a moving average do?','Smooths past prices, with a delay','Guarantees a future price','Removes the possibility of loss'],
 ['RSI: understanding momentum','The Relative Strength Index compares recent gains and losses on a scale from 0 to 100. A common lookback is 14 periods. Readings above 70 are often called overbought and below 30 oversold, but a strong trend can stay in either zone. RSI is a description of recent momentum, not an automatic trade signal.','RSI of 75 can occur while a stock continues rising. Buying or selling solely because of that number can fail.','Separate a descriptive indicator from a prediction.','Does RSI above 70 guarantee a fall?','No; strong momentum can persist','Yes, immediately','Yes, within one candle'],
 ['VWAP: price weighted by volume','Volume Weighted Average Price combines prices with how much traded at those prices, typically from the start of a session. More volume gives a price more weight. Real VWAP needs actual volume and prices. Sprout generates prices and does not supply real exchange volume or a real VWAP feed.','100 shares at $10 and 300 at $12 give VWAP of $11.50: ($1,000 + $3,600) / 400.','Know which data an indicator needs before relying on it.','What gives a price more weight in VWAP?','More shares trading at that price','A longer ticker name','A larger company logo'],
 ['ATR: measuring movement','Average True Range measures the size of price movement, including gaps relative to the previous close. True range is the greatest of high minus low, absolute high minus previous close, and absolute low minus previous close. ATR averages these ranges. It measures movement, not direction.','High $103, low $101, previous close $99: true range is $4. ATR can help compare planned distance to typical movement, but a stop may slip or gap.','A volatile price needs a deliberate size and loss plan.','Does a larger ATR predict rising prices?','No; it measures size of movement','Yes; a larger number means up','Only for ETFs'],
 ['Indicators work better with a plan','Indicators transform past data. Many show overlapping information, and combining them does not eliminate uncertainty. Choose a question, understand the inputs, test a repeatable rule, and set a position size and invalidation point before entering. Avoid adjusting rules to fit a single successful historical chart.','Instead of buying whenever two lines cross, write down the timeframe, what confirms the setup, when you pass, and how much you can lose. Practice both winning and losing examples.','A clear process makes practice useful even when an idea fails.','What should come before a practice entry?','A plan for size, invalidation, and uncertainty','As many indicators as possible','A promise the pattern will work'],
];
export const indicatorLessons:Lesson[]=content.map((c,i)=>({id:55+i,level:12,title:c[0],explanation:c[1],example:c[2],why:c[3],quiz:{question:c[4],options:c.slice(5),answer:0,explanation:c[5]}}));
