"use client";
import {useRouter} from 'next/navigation';
import {useState} from 'react';
import {supabase} from '@/lib/supabase/client';
import {useAccount} from '@/lib/storage/useAccount';
import {billingRequest} from './Subscription';
import Dialog from './Dialog';
import PasswordField from './ui/PasswordField';
export default function AccountSettings(){const {user}=useAccount();const router=useRouter();const [email,setEmail]=useState(''),[current,setCurrent]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[deleting,setDeleting]=useState(false),[confirm,setConfirm]=useState('');
 async function change(kind:'email'|'password'){if(!user)return;setBusy(true);setMessage('');try{const login=await supabase.auth.signInWithPassword({email:user.email!,password:current});if(login.error)throw login.error;const result=await supabase.auth.updateUser(kind==='email'?{email}:{password});if(result.error)throw result.error;setCurrent('');setPassword('');setMessage(kind==='email'?'Check the confirmation instructions sent by email. Your address changes after the required confirmations.':'Your password was updated.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function remove(){if(!user||confirm!=='DELETE')return;setBusy(true);try{const login=await supabase.auth.signInWithPassword({email:user.email!,password:current});if(login.error)throw login.error;const {error}=await supabase.rpc('sprout_delete_account',{confirmation:confirm});if(error){if(error.message.includes('billing account')){await billingRequest('delete-account',{confirmation:confirm});}else if(error.code==='PGRST202')throw Error('Account deletion needs database activation. Your account has not been deleted.');else throw error;}await supabase.auth.signOut();localStorage.removeItem(`sprout-activity-${user.id}`);setDeleting(false);router.replace('/');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="card profile-account"><h2>Account & security</h2>{user?<><p>Signed in as <strong>{user.email}</strong></p><form onSubmit={e=>{e.preventDefault();void change(password?'password':'email');}}><PasswordField label="Current password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} required/><label>New email (optional)<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><PasswordField label="New password (optional)" autoComplete="new-password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/><p className="small">Update one field at a time. Passwords are hidden by default and never saved in your profile.</p><button className="primary" disabled={busy||(!email&&!password)||!!(email&&password)}>Update account</button></form><div className="presentation-actions"><button className="secondary" disabled={busy} onClick={()=>void supabase.auth.signOut()}>Sign out</button><button className="secondary danger" onClick={()=>{setMessage('');setCurrent('');setDeleting(true);}}>Delete account</button></div></>:<p>Sign in below to manage your email, password, or account deletion.</p>}{message&&<p role="status">{message}</p>}{deleting&&<Dialog title="Permanently delete your account" onClose={()=>{if(!busy)setDeleting(false);}}><p>This removes your Sprout login and cloud account data, including community content linked to your account. This cannot be undone. Any linked paid subscriptions will be canceled before deletion. The guest account in this browser is separate.</p><PasswordField label="Current password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)}/><label>Type DELETE to confirm<input value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>{message&&<p role="alert">{message}</p>}<div className="presentation-actions"><button className="secondary" disabled={busy} onClick={()=>setDeleting(false)}>Cancel</button><button className="primary danger" disabled={busy||confirm!=='DELETE'||!current} onClick={()=>void remove()}>{busy?'Deleting…':'Permanently delete'}</button></div></Dialog>}</section>;
}
