"use client";
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import type {Lesson,State} from '@/types';
import {lessons,levels,accountRulesMetadata} from '@/lib/education';
import {presentationQuestions,completePresentation,recordPresentationAttempts} from '@/lib/education/presentation';
import Dialog from './Dialog';
import Sprouty from './Sprouty';
import BeginnerExercise from './BeginnerExercise';
import CandleLessonExample from './CandleLessonExample';
import TutorialVideo from './TutorialVideo';
import tutorials from '@/lib/education/tutorials.json';
export default function LessonPresentation({group,moduleMode,state,update,onClose,onContinue}:{group:Lesson[];moduleMode:boolean;state:State;update:(s:State)=>void|Promise<unknown>;onClose:()=>void;onContinue:(module:boolean)=>void}){
 const router=useRouter();const [slide,setSlide]=useState(0),[phase,setPhase]=useState<'presentation'|'quiz'|'complete'|'results'>('presentation'),[index,setIndex]=useState(0),[answer,setAnswer]=useState<number|null>(null),[checked,setChecked]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[answers,setAnswers]=useState<boolean[]>([]),[score,setScore]=useState(0),[earned,setEarned]=useState(0),[moduleDone,setModuleDone]=useState(false);
 const questions=presentationQuestions(group),q=questions[index],lesson=group[moduleMode?slide:0];
 const slides=moduleMode?group.length:3;
 async function finish(){const finalScore=Math.round(answers.filter(Boolean).length/questions.length*100);setScore(finalScore);const passed=answers.filter(Boolean).length/questions.length>=0.8;setSaving(true);setError('');try{const next=passed?completePresentation(state,group,answers):recordPresentationAttempts(state,state,group,answers);const saved=await update(next);if(saved===false)throw Error('Your progress could not be saved. Please try again.');if(passed){setEarned(next.learning.xp-state.learning.xp);setModuleDone(lessons.filter(l=>l.level===group[0].level).every(l=>next.learning.completed.includes(l.id)));setPhase('complete');}else setPhase('results');}catch(e){setError(e instanceof Error?e.message:'Unable to save progress. Try again.');}finally{setSaving(false);}}

 const correct=answer===q.answer;
 function move(href:string){onClose();router.push(href);}
 return <Dialog title={moduleMode?levels[group[0].level-1]:group[0].title} onClose={onClose}>
 <div className="presentation-progress"><span>{phase==='presentation'?`Presentation · ${slide+1} / ${slides}`:phase==='quiz'?`Quiz · Question ${index+1} / ${questions.length}`:phase==='results'?'Quiz results':'Completed'}</span><progress value={phase==='presentation'?slide+1:phase==='quiz'?index+1:1} max={phase==='presentation'?slides:phase==='quiz'?questions.length:1}/></div>
 {phase==='presentation'&&<><span className="eyebrow">{moduleMode?'MODULE OVERVIEW':'LEARN FIRST'} · {questions.length} quiz question{questions.length===1?'':'s'}</span><h3>{moduleMode?lesson.title:slide===0?'Understand the idea':slide===1?'Explore the example':'Apply what you learned'}</h3>
 {(moduleMode||slide===0)&&<><p className="lesson-copy">{lesson.explanation}</p>{tutorials.find(t=>t.lessonIds.includes(lesson.id))&&<TutorialVideo slug={tutorials.find(t=>t.lessonIds.includes(lesson.id))!.slug}/>}</>}
 {(moduleMode||slide===1)&&<div className="example"><span className="eyebrow">WORKED EXAMPLE</span><p>{lesson.example}</p><CandleLessonExample lessonId={lesson.id}/><BeginnerExercise key={lesson.id} lessonId={lesson.id}/></div>}
 {(moduleMode||slide===2)&&<><div className="tip"><div><strong>Why this matters</strong><p>{lesson.why}</p></div></div><label className="presentation-reflection">Your takeaway (optional, stays here)<textarea key={lesson.id} placeholder="How would you use this idea in practice?"/></label><aside className="lesson-sources"><strong>Explore reliable sources</strong>{[32,39,40,48].includes(lesson.id)?<><p>{accountRulesMetadata.scope}</p>{accountRulesMetadata.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.label} ↗ </a>)}</>:<a href={lesson.level===19||lesson.level===20?'https://www.irs.gov/':lesson.level===35?'https://www.sec.gov/edgar/search/':'https://www.investor.gov/'} target="_blank" rel="noreferrer">{lesson.level===35?'SEC EDGAR public filings':lesson.level===19||lesson.level===20?'IRS tax and retirement guidance':'Investor.gov education'} ↗</a>}</aside></>}
 <div className="presentation-actions"><button className="secondary" disabled={slide===0} onClick={()=>setSlide(slide-1)}>Previous slide</button><button className="primary" onClick={()=>slide+1<slides?setSlide(slide+1):setPhase('quiz')}>{slide+1<slides?'Next slide':'Start quiz'}</button></div></>}
 {phase==='quiz'&&<><p className="small">Pass mark: 80%. Each answer is final for this attempt.</p><h3>{q.question}</h3>{q.visual&&<figure className="scenario-chart"><svg viewBox="0 0 420 180" role="img" aria-label="Illustrative rising price chart approaching resistance at 110 dollars"><path d="M30 145L80 130L125 135L170 100L215 115L260 75L305 60L360 45" fill="none" stroke="var(--primary, #128875)" strokeWidth="4"/><path d="M25 40H395" stroke="#d49236" strokeWidth="2" strokeDasharray="6 5"/><text x="28" y="28" fill="currentColor">Resistance $110</text><text x="28" y="170" fill="currentColor">Earlier → Now · illustrative prices</text></svg><figcaption>A rising price can reverse. No outcome is certain.</figcaption></figure>}
 <div className="quiz-options">{q.options.map((o,i)=><button key={o} className={answer===i?'chosen':''} disabled={checked||saving} onClick={()=>{setAnswer(i);setChecked(false);}}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}</div>
 {checked&&<><Sprouty compact completed={state.learning.completed.length} title={correct?'Nice work. You’ve understood this idea.':'Let’s break this down together.'} message={q.explanation}/><p role="status" className={correct?'success':'error'}>{correct?'Correct.':'Not quite. Review the explanation before the next question.'}</p></>}
 {error&&<p role="alert" className="error">{error}</p>}
 <div className="presentation-actions"><button className="secondary" disabled={saving} onClick={()=>{setPhase('presentation');setSlide(0);}}>Review presentation</button>{checked?<button className="primary" disabled={saving} onClick={()=>{if(index+1===questions.length)void finish();else{setIndex(index+1);setAnswer(null);setChecked(false);}}}>{saving?'Saving progress…':index+1===questions.length?'Finish quiz':'Next question'}</button>:<button className="primary" disabled={answer===null} onClick={()=>{setAnswers([...answers.slice(0,index),correct]);setChecked(true);}}>Check answer</button>}</div></>}
 {phase==='results'&&<section className="presentation-complete"><h3>Quiz score: {score}%</h3><Sprouty compact title="Let’s review this together." message="You need at least 80% to complete this topic. Take a look at the examples, then try again. Your earlier progress stays saved."/><div className="presentation-actions"><button className="primary" onClick={()=>{setPhase('presentation');setSlide(0);setIndex(0);setAnswers([]);setAnswer(null);setChecked(false);}}>Review & retry</button><button className="secondary" onClick={()=>move('/')}>Return to dashboard</button></div></section>}
 {phase==='complete'&&<section className="presentation-complete"><span className="eyebrow">PROGRESS SAVED</span><h3>{moduleDone?'Module complete!':'Lesson complete!'}</h3><p>Quiz score: {score}% · Passed (80% required)</p><p>{moduleDone?`${levels[group[0].level-1]} is complete.`:`You completed ${group[0].title}.`}{earned>0?` You earned ${earned} XP.`:' You’ve reviewed this topic; completion rewards are awarded once.'}</p><Sprouty compact completed={state.learning.completed.length} title="You’re improving. Keep going." message="You took time to understand the idea and practice the decision. Bring that same care to your next step."/><div className="presentation-actions"><button className="primary" onClick={()=>onContinue(moduleDone||moduleMode)}>{moduleDone||moduleMode?'Next module':'Next lesson'}</button><button className="secondary" onClick={()=>move('/market')}>Try the simulator</button><button className="secondary" onClick={()=>move('/')}>Return to dashboard</button></div></section>}
 </Dialog>;
}
