"use client";
import {useState} from 'react';
import Link from 'next/link';
import type {State} from '@/types';
import {lessons,achievements,earned,beginnerLearningOrder} from '@/lib/education';
import Sprouty from './Sprouty';
const fields=[{key:'risk',label:'How comfortable are you with potential losses?',options:['Cautious — help me understand risk','Some familiarity with risk','Comfortable, but want better risk habits']},{key:'time',label:'How much time can you give learning?',options:['5–10 minutes a day','15–30 minutes a day','30+ minutes a day']},{key:'style',label:'How do you prefer to learn?',options:['Visual examples','Reading and worked examples','Hands-on practice']},{key:'goal',label:'What is your main learning goal?',options:['Understand trading from zero','Build personal finance foundations','Improve a trading process']}];
type Choices=Record<string,string>;
function loadPreferences():Choices|null{if(typeof window==='undefined')return null;try{const p=JSON.parse(localStorage.getItem('sprout-learning-preferences')||'null');return p&&fields.every(f=>f.options.includes(p[f.key]))?p:null;}catch{return null;}}
export default function PersonalLearning({state}:{state:State}){
 const [choices,setChoices]=useState<Choices>(()=>loadPreferences()??{}),[saved,setSaved]=useState<Choices|null>(loadPreferences),[editing,setEditing]=useState(false),[notice,setNotice]=useState('');

 const weak=Array.from(new Set(state.learning.attempts.filter(a=>!a.correct).map(a=>a.lessonId))).map(id=>lessons.find(l=>l.id===id)).filter(l=>!!l).slice(0,3);
 const start=saved?.goal===fields[3].options[1]?60:saved?.goal===fields[3].options[2]?137:31;
 const preferred=saved?.goal===fields[3].options[1]?lessons.filter(l=>l.level>=13&&l.level<=22).map(l=>l.id):saved?.goal===fields[3].options[2]?[137,...lessons.filter(l=>l.level>=23).map(l=>l.id)]:beginnerLearningOrder;
 const nextId=[start,...preferred,...beginnerLearningOrder].find(id=>!state.learning.completed.includes(id))??start;
 const next=lessons.find(l=>l.id===nextId)!;
 const badges=achievements.filter(a=>earned(state,a.id));
 return <section className="card personal-learning" id="choose-path"><span className="eyebrow">YOUR NEXT STEP</span><h2>A learning path that fits your day</h2><div className="personal-summary"><div><strong>{state.learning.completed.length} / {lessons.length}</strong><span>Lessons completed</span><progress value={state.learning.completed.length} max={lessons.length}/></div><div><strong>{badges.length}</strong><span>Badges earned</span><small>{badges.slice(-2).map(b=>b.title).join(' · ')||'Your first badge starts with one completed lesson.'}</small></div></div>
 {saved&&<><p>{saved.time} · {saved.style}. {saved.risk===fields[0].options[0]?'Start with foundations and risk planning.':'Build the foundations before increasing practice complexity.'} Suggested difficulty: {saved.goal===fields[3].options[2]?'intermediate review':'beginner'}.</p><Link className="primary" href={`/learn?lesson=${next.id}`}>Continue: {next.title} →</Link><div className="presentation-actions"><Link className="secondary" href={saved.style===fields[2].options[0]?'/learn#tutorials':saved.style===fields[2].options[2]?'/practice#chart-practice':'/learn#curriculum'}>{saved.style===fields[2].options[0]?'Watch visual tutorials':saved.style===fields[2].options[2]?'Open chart practice':'Browse your curriculum'}</Link><Link className="secondary" href="/tools">Practice risk & position sizing</Link></div><button className="secondary" onClick={()=>setEditing(!editing)}>{editing?'Close path quiz':'Retake path quiz'}</button></>}
 {!saved&&!editing&&<div className="presentation-actions"><Link className="primary" href={`/learn?lesson=${next.id}`}>Continue: {next.title} →</Link><button className="secondary" onClick={()=>setEditing(true)}>Choose your path</button></div>}
 {editing&&<form onSubmit={e=>{e.preventDefault();setSaved({...choices});setEditing(false);try{localStorage.setItem('sprout-learning-preferences',JSON.stringify(choices));setNotice('Your path preferences are saved on this browser.');}catch{setNotice('Your path is ready for this visit; browser storage is unavailable.');}}}><p>Four questions, no right or wrong answers. This personalizes education, not investment recommendations.</p>{fields.map(f=><fieldset key={f.key}><legend>{f.label}</legend>{f.options.map(o=><label key={o}><input type="radio" name={f.key} value={o} checked={choices[f.key]===o} onChange={()=>setChoices({...choices,[f.key]:o})} required/>{o}</label>)}</fieldset>)}<button className="primary" disabled={!fields.every(f=>choices[f.key])}>Build my learning path</button></form>}
 {notice&&<p role="status">{notice}</p>}<div className="practice-review"><h3>Topics worth revisiting</h3>{weak.length?<><p>Based on missed quiz answers, not a judgment of your ability.</p>{weak.map(l=><Link key={l!.id} href={`/learn?lesson=${l!.id}`}>{l!.title} →</Link>)}</>:<p>No missed quiz answers recorded yet. Practice a topic to identify areas for review.</p>}</div><Sprouty compact completed={state.learning.completed.length} title="Ready to grow today?" message="Let’s continue where you left off. A short, focused session is a useful next step."/></section>;
}
