"use client";
import {useState,useSyncExternalStore} from 'react';
import Link from 'next/link';
import {Sprout,Leaf,Sun,Moon} from 'lucide-react';
import type {State,Profile} from '@/types';
import {useAccount} from '@/lib/storage/useAccount';
import {lessons,levels} from '@/lib/education';
import {profileInsights} from '@/lib/profile';
import {performance} from '@/lib/trading/analytics';
import {challengeProgress} from '@/lib/education/challenges';
import {money} from '@/lib/market';
import {portfolio} from '@/lib/trading';
import {activitySnapshot,subscribeActivity,readActivity} from '@/lib/activity';
import {supabase} from '@/lib/supabase/client';
import {starterModules,starterLessonIds} from "@/lib/billing/access";
import {ProGate,useSubscription} from "./Subscription";
import AccountSettings from './AccountSettings';
import Sprouty from './Sprouty';
const avatars={sprout:Sprout,leaf:Leaf,sun:Sun,moon:Moon};
export default function ProfileOverview({state,update}:{state:State;update:(s:State)=>void|Promise<unknown>}){
 const {pro}=useSubscription();
 const {user,pending}=useAccount();const [draft,setDraft]=useState<Profile>({...state.profile,timezone:state.profile.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone}),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 const insights=profileInsights(state),stats=performance(state),Avatar=avatars[state.profile.avatar??'sprout'];
 useSyncExternalStore(subscribeActivity,()=>activitySnapshot(state.profile.id),()=> '{}');const activity=readActivity(state.profile.id);
 const times=Intl.supportedValuesOf('timeZone');const joined=user?.created_at||state.profile.joinedAt;
 const counts=[['Modules completed',`${pro?insights.modules:starterModules.filter(m=>m.ids.every(id=>state.learning.completed.includes(id))).length} / ${pro?levels.length:5}`],['Lessons completed',`${pro?state.learning.completed.length:state.learning.completed.filter(id=>starterLessonIds.includes(id)).length} / ${pro?lessons.length:20}`],['Quizzes passed',`${state.learning.quizPasses??state.learning.completed.length}`],['Learning streak',`${state.learning.streak} days`],['Mascot level',`${insights.level} / 4`]];
 async function save(){if(!draft.name.trim()||(draft.handle&&!/^[A-Za-z0-9_]{3,24}$/.test(draft.handle))){setMessage("Enter a display name and a valid optional handle.");return;}setSaving(true);try{const result=await update({...state,profile:{...draft,name:draft.name.trim(),handle:draft.handle?.trim()}});setMessage(result===false?'Profile could not be saved. Try again.':'Profile saved.');}catch{setMessage('Profile could not be saved. Try again.');}finally{setSaving(false);}}
 async function removeListings(){if(!user)return;setSaving(true);const results=await Promise.all([supabase.from('community_portfolios').delete().eq('user_id',user.id),supabase.from('community_scores').delete().eq('user_id',user.id)]);setMessage(results.some(r=>r.error)?'Some listings could not be removed. Please retry.':'Your public leaderboard snapshots were removed.');setSaving(false);}
 return <><section className="card profile-hero"><div className="profile-emblem"><Avatar size={42}/></div><div><span className="eyebrow">YOUR SPROUT IDENTITY</span><h2>{state.profile.name}</h2><p>{state.profile.handle?`@${state.profile.handle}`:'Choose a handle below'} · {user?'Cloud account':'Guest account'}</p>{state.profile.bio&&<p>{state.profile.bio}</p>}<small>Joined {joined?new Date(joined).toLocaleDateString(): 'date not recorded'}{state.profile.country?` · ${state.profile.country}`:''}</small></div></section>
 <section className="card profile-edit"><h2>Profile details</h2><form onSubmit={e=>{e.preventDefault();void save();}}><fieldset><legend>Choose your avatar</legend><div className="avatar-options">{Object.entries(avatars).map(([id,Icon])=><button type="button" key={id} aria-label={`${id} avatar`} aria-pressed={(draft.avatar??'sprout')===id} onClick={()=>setDraft({...draft,avatar:id as Profile['avatar']})}><Icon size={26}/></button>)}</div></fieldset><div className="profile-fields"><label>Display name<input required maxLength={30} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Username / handle<input maxLength={24} pattern="[A-Za-z0-9_]{3,24}" placeholder="e.g. mindful_trader" value={draft.handle||''} onChange={e=>setDraft({...draft,handle:e.target.value})}/><small>Optional display handle, 3–24 letters, numbers, or underscores. Handles are not unique account logins.</small></label><label>Bio (optional)<textarea maxLength={240} value={draft.bio||''} onChange={e=>setDraft({...draft,bio:e.target.value})} placeholder="What are you learning toward?"/></label><label>Country<input maxLength={80} value={draft.country||''} onChange={e=>setDraft({...draft,country:e.target.value})}/></label><label>Timezone<select value={draft.timezone||'UTC'} onChange={e=>setDraft({...draft,timezone:e.target.value})}><option>UTC</option>{times.map(t=><option key={t}>{t}</option>)}</select></label></div><button className="primary" disabled={saving||pending||!draft.name.trim()}>{saving?'Saving…':'Save profile'}</button></form>{message&&<p role="status">{message}</p>}</section>
 <section className="card profile-learning"><h2>Your learning growth</h2><progress aria-label="Learning path progress" value={pro?state.learning.completed.length:state.learning.completed.filter(id=>starterLessonIds.includes(id)).length} max={pro?lessons.length:20}/><div className="analytics-grid">{counts.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="small">Completed lessons and modules reflect passed quizzes. Quiz passes include successful reviews; older records use completed lessons as their historical baseline; a learning streak measures days with quiz activity.</p><Sprouty completed={state.learning.completed.length}/></section>
 <ProGate feature="Full simulator analytics"><section className="card profile-performance"><h2>Simulator performance</h2><div className="analytics-grid">{[['Win rate',stats.winRate===null?'—':`${stats.winRate.toFixed(1)}%`],['Average R',stats.averageR===null?'—':`${stats.averageR.toFixed(2)}R`],['Best trade',stats.bestTrade?money(stats.bestTrade.realized):'—'],['Worst trade',stats.worstTrade?money(stats.worstTrade.realized):'—'],['Total trades taken',String(state.trades.length)],['Behavior risk score',insights.risk===null?'—':`${insights.risk} / 100`]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p>Current portfolio goal: {state.returnGoal?`${Math.max(0,Math.min(100,(portfolio(state).value-state.returnGoal.startingEquity)/(state.returnGoal.startingEquity*state.returnGoal.targetPercent/100)*100)).toFixed(1)}% toward +${state.returnGoal.targetPercent}% virtual equity`:'No active equity goal.'}</p><p>Practice challenge: {state.challenge?`${state.challenge.id==='plan-3'?'Three-trade journal review':'Seven-day reflection'} · ${challengeProgress(state)} / ${state.challenge.id==='plan-3'?3:7} reviewed`:'No active journal challenge.'}</p><Link href="/practice">View challenge progress →</Link><p className="small">Win rate describes non-breakeven sell fills; R needs a journaled initial risk. Best/worst show realized dollars. Risk score is a reflection prompt: up to 40 points for missing journaled risk, 40 for fills less than a minute apart, and 20 for recent self-reported Tilt. Higher means more behaviors to review, not a prediction or professional assessment.</p></section></ProGate>
 {!state.profile.hideProfileInsights&&<section className="card profile-insights"><h2>Study habits & learning insights</h2><div className="profile-fields"><div><h3>Most studied topics</h3>{insights.topics.length?insights.topics.map(t=><p key={t.name}>{t.name} · {t.count} question attempts</p>):<p>Complete a quiz to start your topic history.</p>}</div><div><h3>Areas to revisit</h3>{insights.weak.length?insights.weak.map(l=><Link key={l.id} href={`/learn?lesson=${l.id}`}>{l.title} →</Link>):<p>No missed answers recorded yet.</p>}</div><div><h3>Active learning time</h3><strong>{Math.floor(activity.learning/60)} min</strong></div><div><h3>Active simulator time</h3><strong>{Math.floor(activity.simulator/60)} min</strong></div></div><p className="small">Time is counted from this update on this browser while the tab is focused and recently used; earlier sessions are not estimated.</p><h3>Recommended next lesson</h3><Link className="secondary" href={`/learn?lesson=${insights.weak[0]?.id??lessons.find(l=>!state.learning.completed.includes(l.id))?.id??1}`}>{insights.weak[0]?.title??lessons.find(l=>!state.learning.completed.includes(l.id))?.title??'Review trading basics'} →</Link></section>}
 <section className="card profile-privacy"><h2>Notifications & privacy</h2><label><input type="checkbox" checked={draft.achievementNotifications!==false} onChange={e=>setDraft({...draft,achievementNotifications:e.target.checked})}/> In-app achievement notifications</label><label><input type="checkbox" checked={!!draft.hideProfileInsights} onChange={e=>setDraft({...draft,hideProfileInsights:e.target.checked})}/> Hide study insights on my profile</label><p className="small">Save profile to apply these settings. Profile details, learning data, and journals are private. Community posts and explicitly shared leaderboard snapshots are public. These settings do not send email notifications.</p><button className="primary" disabled={saving||pending} onClick={()=>void save()}>Save preferences</button>{user&&<button className="secondary" disabled={saving} onClick={()=>void removeListings()}>Remove my public leaderboard snapshots</button>}</section><AccountSettings/></>;
}
