"use client";
import {useEffect,useRef,useState} from 'react';
import {ExternalLink,RefreshCw} from 'lucide-react';
const groups=[
 {name:'Stocks',symbols:[['NASDAQ:AAPL','Apple'],['NASDAQ:MSFT','Microsoft'],['NASDAQ:NVDA','NVIDIA'],['NASDAQ:AMZN','Amazon'],['NASDAQ:GOOGL','Alphabet'],['NASDAQ:META','Meta'],['NASDAQ:TSLA','Tesla'],['NASDAQ:AMD','AMD'],['NASDAQ:AVGO','Broadcom'],['NYSE:JPM','JPMorgan'],['NYSE:WMT','Walmart'],['NYSE:XOM','Exxon Mobil']]},
 {name:'ETFs',symbols:[['AMEX:SPY','S&P 500 ETF'],['AMEX:VOO','Vanguard S&P 500'],['NASDAQ:QQQ','Nasdaq 100 ETF'],['AMEX:VTI','Total US stock market'],['AMEX:IWM','Russell 2000 ETF'],['AMEX:GLD','Gold ETF'],['NASDAQ:TLT','Long-term Treasuries'],['NASDAQ:BND','Total bond market']]},
 {name:'Futures',symbols:[['CME_MINI:ES1!','S&P 500 E-mini'],['CME_MINI:NQ1!','Nasdaq 100 E-mini'],['CBOT_MINI:YM1!','Dow E-mini'],['CME_MINI:RTY1!','Russell 2000 E-mini'],['NYMEX:CL1!','WTI crude oil'],['COMEX:GC1!','Gold']]}
];
export default function RealMarketQuotes(){
 const host=useRef<HTMLDivElement>(null);const [failed,setFailed]=useState(false),[reload,setReload]=useState(0);
 useEffect(()=>{
  const element=host.current;
  function load(){if(!element)return;setFailed(false);element.replaceChildren();const widget=document.createElement('div');widget.className='tradingview-widget-container__widget';element.appendChild(widget);const script=document.createElement('script');script.src='https://s3.tradingview.com/external-embedding/embed-widget-market-quotes.js';script.async=true;script.textContent=JSON.stringify({width:'100%',height:550,symbolsGroups:groups.map(g=>({name:g.name,symbols:g.symbols.map(([name,displayName])=>({name,displayName}))})),showSymbolLogo:true,isTransparent:false,colorTheme:document.documentElement.dataset.theme==='dark'?'dark':'light',locale:'en'});script.onerror=()=>setFailed(true);element.appendChild(script);}
  load();window.addEventListener('sprout-theme',load);return()=>{window.removeEventListener('sprout-theme',load);element?.replaceChildren();};
 },[reload]);
 return <section className="card real-market-quotes"><div className="page-heading"><div><span className="eyebrow">EXTERNAL MARKET QUOTES</span><h2>Stocks, ETFs & futures</h2><p>Exchange market data supplied by TradingView. Quotes may be delayed by the exchange or provider; check each symbol’s timestamp and data status. Markets do not move continuously outside their trading sessions.</p></div><button className="secondary" onClick={()=>setReload(n=>n+1)}><RefreshCw size={16}/>Reload quotes</button></div><div ref={host} className="tradingview-widget-container" aria-label="TradingView stocks, ETFs and futures market quotes"/>{failed&&<p role="status">The quote widget could not load. Use the market-source links below to check prices.</p>}<a href="https://www.tradingview.com/markets/" target="_blank" rel="noopener noreferrer">Market quotes by TradingView <ExternalLink size={14}/></a><p className="small">These quotes are for research. Virtual trades still use Sprout’s generated practice prices, which can differ from these quotes. Futures symbols here are continuous chart references, not executable contracts; Sprout does not currently offer futures trading.</p><details><summary>Open quotes on Yahoo Finance</summary><div className="real-quote-links">{groups.map(g=><div key={g.name}><h3>{g.name}</h3>{g.symbols.map(([symbol,label])=>{const ticker=symbol.split(':')[1];const yahoo=({'ES1!':'ES=F','NQ1!':'NQ=F','YM1!':'YM=F','RTY1!':'RTY=F','CL1!':'CL=F','GC1!':'GC=F'} as Record<string,string>)[ticker]??ticker;return <a key={symbol} href={`https://finance.yahoo.com/quote/${encodeURIComponent(yahoo)}/`} target="_blank" rel="noopener noreferrer">{label}<ExternalLink size={12}/></a>;})}</div>)}</div></details></section>;
}
