"use client";
import {useState,useEffect} from 'react';
import {Gift,Copy} from 'lucide-react';
import {useAccount} from '@/lib/storage/useAccount';
import {supabase} from '@/lib/supabase/client';
export default function ReferralCard(){const {user}=useAccount();const [code,setCode]=useState(''),[saved,setSaved]=useState(''),[friends,setFriends]=useState(0),[message,setMessage]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;if(user)supabase.rpc('sprout_referral_status').then(({data,error})=>{if(!active)return;if(error||data?.version!==2){setReady(false);return;}setCode(data.code);setSaved(data.code);setFriends(data.friends);setReady(true);});return()=>{active=false;};},[user]);
 async function save(){setBusy(true);setMessage('');try{const {data,error}=await supabase.rpc('sprout_customize_referral',{input_code:code});if(error)throw error;setSaved(data);setCode(data);setMessage('Your personal code is saved. Share it with a new learner.');}catch(e){setMessage(e instanceof Error?e.message:'That code could not be saved. It may already be taken.');}finally{setBusy(false);}}
 return <section className="card referral-card" id="referrals"><span className="referral-icon"><Gift size={34}/></span><div><span className="eyebrow">GROW TOGETHER</span><h2>Your code. Their first $5,000 bonus.</h2><p>Choose a personal referral code and share it with a friend. When they enter it during signup and confirm their email, their simulator receives an extra $5,000 in virtual practice cash.</p><span className="badge">VIRTUAL MONEY · NO CASH VALUE</span><p className="small">One signup bonus per new account, claimed within seven days. No self-referrals. The bonus goes to the new learner and does not count as trading profit.</p>{!user?<a href="#account" className="primary">Sign in to create your code</a>:!ready?<p role="status">Personal referral codes are awaiting activation.</p>:<><form onSubmit={e=>{e.preventDefault();void save();}}><label htmlFor="personal-referral-code">Your personal code</label><div className="referral-code"><input id="personal-referral-code" aria-label="Personal referral code" required minLength={3} maxLength={24} pattern="[A-Za-z0-9_]{3,24}" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><button className="primary" disabled={busy||code===saved}>{busy?'Saving…':'Save code'}</button></div><small>3–24 letters, numbers or underscores. Each code is unique.</small></form><div className="referral-code"><strong>{saved}</strong><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(saved);setMessage('Code copied. Your friend can enter it during signup.');}catch{setMessage('Select the code above to copy it.');}}}><Copy size={16}/>Copy code</button></div><p>{friends} {friends===1?'friend has':'friends have'} joined with your code.</p></>}{message&&<p role="status">{message}</p>}</div></section>;
}
