"use client";
import {useState,useEffect,useCallback} from 'react';
import {Gift,Copy,Users} from 'lucide-react';
import {useAccount} from '@/lib/storage/useAccount';
import {supabase} from '@/lib/supabase/client';
import {communityStatus} from '@/lib/community/status';
import {money} from '@/lib/market';
interface Status {userId?:string;code:string;friends:number;bonus:number;redeemed:boolean;}
export default function ReferralCard(){const {user,state,pending,retry}=useAccount();const [status,setStatus]=useState<Status|null>(null),[available,setAvailable]=useState<boolean|null>(null),[code,setCode]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!user){const readiness=await communityStatus();setAvailable(readiness.referrals);return;}if(!state)return;const {data,error}=await supabase.rpc('sprout_referral_status');setAvailable(!error);if(!error&&data&&typeof data.code==="string")setStatus({...data,userId:user.id} as Status);else setAvailable(false);},[user,state]);
 useEffect(()=>{let active=true;void Promise.resolve().then(()=>{if(active)return load();});return()=>{active=false;};},[load]);
 async function redeem(){if(!user||busy||pending||!code.trim())return;setBusy(true);const {data,error}=await supabase.rpc('sprout_redeem_referral',{input_code:code.trim().toUpperCase()});setBusy(false);setMessage(error?error.message:`Your friend received ${money(Number(data.awarded))} in virtual cash. Thanks for learning together!`);if(!error){setCode('');await load();}}
 return <section className="card referral-card" id="referrals"><span className="referral-icon"><Gift size={34}/></span><div><span className="eyebrow">GROW TOGETHER</span><h2>Refer a friend. Get $10,000 in virtual cash.</h2><p>Share your code with a new learner. When they create an account, confirm their email, and redeem it, your simulator gets a $10,000 practice-cash bonus.</p><span className="badge">SIMULATED MONEY · NO CASH VALUE</span>{available!==true&&<p className="referral-pending" role="status">Coming soon: referral rewards are awaiting activation.</p>}<p className="small">One code per new account, within seven days of joining. Self-referrals do not qualify. Bonuses are deposits, not trading profits, and end any active portfolio return goal.</p>
 {!user?<a className="primary" href="#account">Create your account <Users size={17}/></a>:available===false?null:status?.userId===user?.id?<><div className="referral-code"><strong>{status.code}</strong><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(status.code);setMessage('Referral code copied.');}catch{setMessage('Select your code above to copy it.');}}}><Copy size={16}/> Copy code</button></div><p>{status.friends} {status.friends===1?"friend":"friends"} · {money(status.bonus)} virtual bonus awarded</p><button className="text-link" disabled={busy||pending} onClick={()=>{retry();setMessage('Refreshing your account and referral balance…');}}>Refresh my bonus balance</button>{!status.redeemed&&<form onSubmit={e=>{e.preventDefault();void redeem();}}><label htmlFor="referral-input">Have a friend’s code?</label><div className="referral-code"><input id="referral-input" autoCapitalize="characters" maxLength={12} value={code} onChange={e=>setCode(e.target.value.replace(/[^a-z0-9]/gi,''))} placeholder="Enter referral code"/><button className="primary" disabled={busy||pending||code.length!==12}>Redeem code</button></div></form>}</>:<p role="status">Loading your referral code…</p>}
 {message&&<p role="status">{message}</p>}</div></section>}
