"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {createChart,CandlestickSeries,BarSeries,LineSeries,HistogramSeries,createSeriesMarkers,ColorType,type IPriceLine,type IChartApi,type ISeriesApi,type SeriesType,type UTCTimestamp} from 'lightweight-charts';
import {chartBars,indicators,heikinAshi,patternTags,riskPlan,intervals,type Interval,type Bar} from '@/lib/chart/analysis';
import {chartTour,starterTourSteps} from '@/lib/chart/tour';
import {money} from '@/lib/market';
import type {State} from '@/types';
import {useSubscription} from './Subscription';
import SimpleCandlestickChart from "./CandlestickChart";
import Sprouty from './Sprouty';
type Tool='cursor'|'horizontal'|'vertical'|'trend'|'rectangle'|'fib'|'brush'|'text'|'arrow'|'label';
type Point={time:number;price:number};
type Drawing={tool:Tool;points:Point[];text?:string};
const options=['SMA','EMA','VWAP','MACD','Supertrend','RSI','Stochastic','CCI','Bollinger','ATR','Volume','VolumeMA','VolumeProfile','VolumeHeatmap'];
const colors=['#36a992','#ca9c50','#8e7bdb','#5194d2','#cf798d'];
export default function TradingChart({ticker,state}:{ticker:string;state:State}){
 const {pro,upgrade}=useSubscription();const host=useRef<HTMLDivElement>(null),shell=useRef<HTMLDivElement>(null),chart=useRef<IChartApi|null>(null),main=useRef<ISeriesApi<SeriesType>|null>(null),extras=useRef<{name:string;series:ISeriesApi<SeriesType>}[]>([]),dataRef=useRef<Bar[]>([]);
 const [interval,setInterval]=useState<Interval>('1m'),[style,setStyle]=useState('candles'),[panel,setPanel]=useState(''),[selected,setSelected]=useState<string[]>([]),[period,setPeriod]=useState(20),[grid,setGrid]=useState(true),[auto,setAuto]=useState(true),[bull,setBull]=useState('#22a77a'),[bear,setBear]=useState('#e36a78'),[wick,setWick]=useState(1),[dark,setDark]=useState(false),[hover,setHover]=useState<Bar|null>(null),[revision,setRevision]=useState(0),[tool,setTool]=useState<Tool>('cursor'),[drawings,setDrawings]=useState<Drawing[]>([]),[anchor,setAnchor]=useState<Point|null>(null),[note,setNote]=useState('My chart note'),[showTags,setShowTags]=useState(false),[entry,setEntry]=useState(''),[stop,setStop]=useState(''),[target,setTarget]=useState(''),[size,setSize]=useState('1'),[replay,setReplay]=useState<number|null>(null),[replayData,setReplayData]=useState<Bar[]|null>(null),[replayTick,setReplayTick]=useState<number|null>(null),[comparison,setComparison]=useState(''),[alert,setAlert]=useState(''),[alertNotice,setAlertNotice]=useState(''),[tour,setTour]=useState<number|null>(null),[projected,setProjected]=useState<{drawing:Drawing;points:{x:number;y:number}[]}[]>([]),[wickPixels,setWickPixels]=useState<{x:number;high:number;low:number;color:string}[]>([]);
 const full=useMemo(()=>chartBars(ticker,interval,state.tick),[ticker,interval,state.tick]);const data=useMemo(()=>replay===null?full:(replayData??full).slice(0,Math.max(20,replay)),[full,replay,replayData]);const values=useMemo(()=>indicators(data,period),[data,period]);const transformed=useMemo(()=>style==='heikin'?heikinAshi(data):data,[style,data]);const last=data.at(-1)!,read=hover??last;
 const plan=useMemo(()=>riskPlan(Number(entry),Number(stop),Number(target),Number(size)),[entry,stop,target,size]);const toolset=pro?selected:[];
 useEffect(()=>{const update=()=>setDark(document.documentElement.dataset.theme==='dark');update();window.addEventListener('sprout-theme',update);return()=>window.removeEventListener('sprout-theme',update);},[]);
 useEffect(()=>{
  const element=host.current;if(!element)return;const c=createChart(element,{autoSize:true,height:480,layout:{background:{type:ColorType.Solid,color:dark?'#142432':'#ffffff'},textColor:dark?'#cbdbe4':'#344a4c',attributionLogo:true},grid:{vertLines:{visible:grid},horzLines:{visible:grid}},timeScale:{timeVisible:true,secondsVisible:interval==='30s'},rightPriceScale:{autoScale:auto},crosshair:{mode:0}});chart.current=c;
  const series=style==='line'?c.addSeries(LineSeries,{color:bull}):style==='bars'?c.addSeries(BarSeries,{upColor:bull,downColor:bear}):c.addSeries(CandlestickSeries,{upColor:bull,downColor:bear,borderUpColor:bull,borderDownColor:bear,wickUpColor:bull,wickDownColor:bear});main.current=series as ISeriesApi<SeriesType>;
  const add=(name:string,pane=0,color=colors[extras.current.length%colors.length])=>{const series=c.addSeries(LineSeries,{color,lineWidth:1,priceLineVisible:false,lastValueVisible:false},pane);extras.current.push({name,series:series as ISeriesApi<SeriesType>});};let pane=1;extras.current=[];
  for(const name of pro?selected:[]){if(name==='Bollinger'){add('SMA');add('BollingerUpper');add('BollingerLower');}else if(name==='MACD'){add('MACD',pane);add('Signal',pane++);}else if(['RSI','Stochastic','CCI','ATR'].includes(name))add(name,pane++);else if(name==='Volume'){const series=c.addSeries(HistogramSeries,{priceFormat:{type:'volume'},priceLineVisible:false,lastValueVisible:false},pane++);extras.current.push({name,series:series as ISeriesApi<SeriesType>});}else if(name==='VolumeMA')add(name,pane++);else if(!['VolumeProfile','VolumeHeatmap'].includes(name))add(name);}
  if(pro&&comparison)add('Compare',0,'#8e7bdb');
  c.subscribeCrosshairMove(event=>{const item=dataRef.current.find(b=>b.time===event.time);setHover(item??null);});c.timeScale().subscribeVisibleLogicalRangeChange(()=>setRevision(n=>n+1));
  return()=>{main.current=null;extras.current=[];chart.current=null;c.remove();};
 },[dark,grid,auto,bull,bear,style,interval,pro,selected,comparison]);
 useEffect(()=>{dataRef.current=data;const m=main.current,c=chart.current;if(!m||!c)return;m.setData(transformed.map(b=>style==='line'?{time:b.time as UTCTimestamp,value:b.close}:{time:b.time as UTCTimestamp,open:b.open,high:b.high,low:b.low,close:b.close}));for(const item of extras.current){const points=item.name==='Compare'?(()=>{const other=chartBars(comparison,interval,replayTick??state.tick);return other.slice(0,data.length).map((b,i)=>({time:data[i].time as UTCTimestamp,value:b.close/other[0].close*data[0].close}));})():data.flatMap((b,i)=>{const value=item.name==='Volume'?b.volume:values[item.name as keyof typeof values]?.[i];return value===null||value===undefined?[]:[{time:b.time as UTCTimestamp,value,color:b.close>=b.open?bull:bear}];});item.series.setData(points);}
  const markers=state.trades.filter(t=>t.ticker===ticker).flatMap(t=>{const timestamp=new Date(t.date).getTime()/1000;const index=data.findLastIndex(b=>b.time<=timestamp);if(index<0||timestamp>last.time+intervals[interval]*2)return [];return [{time:data[index].time as UTCTimestamp,position:t.side==='buy'?'belowBar' as const:'aboveBar' as const,color:t.side==='buy'?bull:bear,shape:t.side==='buy'?'arrowUp' as const:'arrowDown' as const,text:`${t.side} ${t.shares} @ ${money(t.price)}`}];});if(pro&&showTags)for(const tag of patternTags(data).slice(-15))markers.push({time:data[tag.index].time as UTCTimestamp,position:'aboveBar',color:'#bf944c',shape:'arrowDown',text:tag.label});markers.sort((a,b)=>Number(a.time)-Number(b.time));const markerApi=createSeriesMarkers(m,markers);
  const lines:IPriceLine[]=[];if(pro&&plan){for(const [price,title,color] of [[Number(entry),'Planned entry','#5194d2'],[Number(stop),'Planned stop','#e36a78'],[Number(target),'Planned target','#22a77a']] as const)lines.push(m.createPriceLine({price,color,lineWidth:1,lineStyle:2,axisLabelVisible:true,title}));}
  setRevision(n=>n+1);return()=>{if(chart.current!==c)return;markerApi.detach();for(const line of lines)m.removePriceLine(line);};
 },[data,style,transformed,values,state.trades,ticker,interval,state.tick,last.time,replayTick,bull,bear,pro,showTags,comparison,plan,entry,stop,target,dark,grid,auto,selected]);
 useEffect(()=>{if(!pro||!alert)return;const price=Number(alert);if(price>0&&last.high>=price&&last.low<=price){const timer=window.setTimeout(()=>{setAlertNotice(`Practice price touched ${money(price)}. This is a browser-only alert.`);setAlert('');},0);return()=>window.clearTimeout(timer);}},[last,pro,alert]);
 function paid(action:()=>void){if(!pro){upgrade('Advanced chart tools');return;}action();}
 function open(name:string){setPanel(panel===name?'':name);}
 function brush(e:React.PointerEvent<SVGSVGElement>,start=false){if(!pro||tool!=='brush'||(!start&&e.buttons!==1))return;const rect=e.currentTarget.getBoundingClientRect(),time=chart.current?.timeScale().coordinateToTime(e.clientX-rect.left),price=main.current?.coordinateToPrice(e.clientY-rect.top);if(typeof time!=='number'||price===null||price===undefined)return;const point={time:Number(time),price};if(start){e.currentTarget.setPointerCapture(e.pointerId);setDrawings(d=>[...d,{tool:'brush',points:[point]}]);}else setDrawings(d=>{const last=d.at(-1);return last?.tool==='brush'?[...d.slice(0,-1),{...last,points:[...last.points,point]}]:d;});}
 function draw(e:React.MouseEvent<SVGSVGElement>){if(!pro||tool==='cursor'||tool==='brush')return;const rect=e.currentTarget.getBoundingClientRect(),time=chart.current?.timeScale().coordinateToTime(e.clientX-rect.left),price=main.current?.coordinateToPrice(e.clientY-rect.top);if(typeof time!=='number'||price===null||price===undefined)return;const point={time:Number(time),price};if(['horizontal','vertical','text','label'].includes(tool)){setDrawings(d=>[...d,{tool,points:[point],text:note}]);return;}if(anchor){setDrawings(d=>[...d,{tool,points:[anchor,point],text:note}]);setAnchor(null);}else setAnchor(point);}
 useEffect(()=>{const c=chart.current,m=main.current;if(!c||!m)return;setProjected(drawings.flatMap(d=>{const points=d.points.map(p=>({x:c.timeScale().timeToCoordinate(p.time as UTCTimestamp),y:m.priceToCoordinate(p.price)}));return points.every(p=>p.x!==null&&p.y!==null)?[{drawing:d,points:points as {x:number;y:number}[]}]:[];}));setWickPixels(wick>1&&['candles','heikin'].includes(style)?transformed.flatMap(b=>{const x=c.timeScale().timeToCoordinate(b.time as UTCTimestamp),high=m.priceToCoordinate(b.high),low=m.priceToCoordinate(b.low);return x!==null&&high!==null&&low!==null?[{x,high,low,color:b.close>=b.open?bull:bear}]:[];}):[]);},[revision,drawings,wick,transformed,style,bull,bear]);

 const tourStep=tour===null?null:chartTour[tour],lockedTour=tour!==null&&tour>=starterTourSteps&&!pro;
 function nextTour(){if(tour===null)return;if(tour===7&&!pro){setTour(8);return;}if(tour===15){setTour(null);setPanel('');return;}setTour(tour+1);setPanel(chartTour[tour+1][2]);}
 return <div className="trading-chart-workspace" ref={shell} data-tour-target={tourStep?.[2]}>
 <div className="chart-workspace-toolbar"><label data-chart-tool="interval">Interval<select aria-label="Candle interval" value={interval} onChange={e=>{setInterval(e.target.value as Interval);setHover(null);}}>{Object.keys(intervals).map(i=><option key={i}>{i}</option>)}</select></label><button onClick={()=>{const range=chart.current?.timeScale().getVisibleLogicalRange();if(range&&range.to-range.from>25)chart.current?.timeScale().setVisibleLogicalRange({from:range.from+10,to:range.to-10});}}>Zoom in</button><button onClick={()=>{const range=chart.current?.timeScale().getVisibleLogicalRange();if(range)chart.current?.timeScale().setVisibleLogicalRange({from:range.from-10,to:range.to+10});}}>Zoom out</button><button onClick={()=>{const range=chart.current?.timeScale().getVisibleLogicalRange();if(range)chart.current?.timeScale().setVisibleLogicalRange({from:range.from-20,to:range.to-20});}}>Earlier</button><button onClick={()=>chart.current?.timeScale().scrollToRealTime()}>Latest</button><button onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void shell.current?.requestFullscreen().catch(()=>setAlertNotice('Full screen is unavailable in this browser.'));}}>Full screen</button><button onClick={()=>{setTour(0);setPanel('');}}>Sprouty chart tour</button></div>
 <div className="chart-workspace-tabs">{['indicators','drawings','risk','replay','advanced','settings'].map(name=><button key={name} aria-expanded={panel===name} className={panel===name?'active':''} onClick={()=>open(name)}>{name[0].toUpperCase()+name.slice(1)}{name!=='settings'&&!pro?' · Pro':''}</button>)}</div>
 {tourStep&&<aside className="chart-tour" role="region" aria-label="Sprouty interactive chart tour"><Sprouty compact title={`${tour!+1} / 16 · ${tourStep[0]}`} message={lockedTour?'You completed the 8 free chart-tour steps. The remaining 8 steps cover Pro chart tools.':tourStep[1]}/>{lockedTour?<><button className="primary" onClick={()=>upgrade('The final 8 interactive chart-tour steps')}>Unlock Pro tour</button><button onClick={()=>{setTour(null);setPanel('');}}>Finish Starter tour</button></>:<><button onClick={()=>{setPanel(tourStep[2]==='chart'?'':tourStep[2]);if(tour===2)setInterval('5m');if(tour===3){const r=chart.current?.timeScale().getVisibleLogicalRange();if(r)chart.current?.timeScale().setVisibleLogicalRange({from:r.from+5,to:r.to-5});}if(tour===4)chart.current?.timeScale().scrollToPosition(-20,false);}}>Try this step</button><button className="primary" onClick={nextTour}>{tour===15?'Finish tour':'Next step'}</button><button onClick={()=>setTour(null)}>Exit tour</button></>}</aside>}
 {panel==='indicators'&&<section className="chart-tools-panel"><h3>Indicators</h3><p>Calculated from generated practice prices and activity; not signals or exchange volume.</p><label>Average / band period<input type="number" min="2" max="60" value={period} onChange={e=>paid(()=>setPeriod(Math.max(2,Math.min(60,Number(e.target.value)||20))))}/></label><div className="indicator-options">{options.map(name=><label key={name}><input type="checkbox" checked={toolset.includes(name)} onChange={()=>paid(()=>setSelected(s=>s.includes(name)?s.filter(n=>n!==name):[...s,name]))}/>{name}</label>)}</div></section>}
 {panel==='settings'&&<section className="chart-tools-panel"><h3>Chart settings</h3><label>Chart type<select value={style} onChange={e=>setStyle(e.target.value)}><option value="candles">Candles</option><option value="bars">OHLC bars</option><option value="line">Line</option><option value="heikin">Heikin-Ashi</option></select></label><label>Bullish color<input type="color" value={bull} onChange={e=>setBull(e.target.value)}/></label><label>Bearish color<input type="color" value={bear} onChange={e=>setBear(e.target.value)}/></label><label>Wick display<input type="range" min="1" max="3" value={wick} onChange={e=>setWick(Number(e.target.value))}/></label><label><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/>Grid lines</label><label><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>Auto-scale</label><p>Chart background follows your website light/dark theme. Heikin-Ashi prices are transformed; trades use the original simulated quote.</p></section>}
 {panel==='drawings'&&<section className="chart-tools-panel"><h3>Draw on the chart</h3><p>One click for a horizontal line, vertical line, note or label. Two clicks for a trend line, rectangle, Fibonacci or arrow. Drag to free-draw with the brush. Drawings are temporary learning annotations.</p><label>Drawing tool<select value={tool} onChange={e=>paid(()=>{setTool(e.target.value as Tool);setAnchor(null);})}>{['cursor','horizontal','vertical','trend','rectangle','fib','brush','text','arrow','label'].map(t=><option key={t}>{t}</option>)}</select></label><label>Annotation text<input maxLength={80} value={note} onChange={e=>setNote(e.target.value)}/></label><button onClick={()=>paid(()=>setDrawings(d=>d.slice(0,-1)))}>Undo drawing</button><button onClick={()=>paid(()=>{setDrawings([]);setAnchor(null);})}>Clear drawings</button>{anchor&&<p role="status">First point set. Click a second point.</p>}</section>}
 {panel==='risk'&&<section className="chart-tools-panel"><h3>Plan risk / reward</h3>{[['Entry',entry,setEntry],['Stop',stop,setStop],['Target',target,setTarget],['Position size',size,setSize]].map(([name,value,setter])=><label key={String(name)}>{String(name)}<input type="number" min="0" step="any" value={String(value)} onChange={e=>paid(()=>(setter as (v:string)=>void)(e.target.value))}/></label>)}{plan&&pro?<p>Planned risk {money(plan.risk)} · reward {money(plan.reward)} · {plan.ratio.toFixed(2)}R · {plan.direction}. Planning only; stop/target lines do not execute orders.</p>:<p>Enter valid entry, stop, target and size to review risk. Recorded fills appear as entry/exit arrows.</p>}</section>}
 {panel==='replay'&&<section className="chart-tools-panel"><h3>Bar-by-bar replay</h3><button onClick={()=>paid(()=>{setReplayData(full);setReplayTick(state.tick);setReplay(30);})}>Start replay</button><button disabled={replay===null} onClick={()=>paid(()=>setReplay(n=>n===null?null:Math.min(full.length,n+1)))}>Next bar</button><button onClick={()=>{setReplay(null);setReplayData(null);setReplayTick(null);}}>Return to current chart</button><p>Replay is chart-only. Order tickets and portfolio valuation continue using the current simulated quote.</p></section>}
 {panel==='advanced'&&<section className="chart-tools-panel"><h3>Learning overlays & alerts</h3><label><input type="checkbox" checked={pro&&showTags} onChange={e=>paid(()=>setShowTags(e.target.checked))}/>Pattern candidates</label><p>Heuristics can misclassify patterns and do not establish a profitable entry. Flag, pennant and triangle structures can be annotated with trend lines.</p><label>Compare ticker<select value={comparison} onChange={e=>paid(()=>setComparison(e.target.value))}><option value="">None</option>{['AAPL','MSFT','NVDA','SPY','QQQ','BTC-USD','ETH-USD'].filter(t=>t!==ticker).map(t=><option key={t}>{t}</option>)}</select></label><p>Comparison is normalized to the first visible starting price, not a second execution quote.</p><label>Practice price alert<input type="number" min="0" step="any" value={alert} onChange={e=>paid(()=>setAlert(e.target.value))}/></label><p>Alerts run only while this page is open. No background notifications or exchange order book are provided.</p></section>}
 <div className="chart-ohlc" aria-live="off"><strong>{ticker}</strong><span>O {money(read.open)}</span><span>H {money(read.high)}</span><span>L {money(read.low)}</span><span>C {money(read.close)}</span><span>Body {money(Math.abs(read.close-read.open))}</span><span>Upper wick {money(read.high-Math.max(read.open,read.close))}</span><span>Lower wick {money(Math.min(read.open,read.close)-read.low)}</span></div>
 <div className="native-chart-frame" role="img" aria-label="Simulated candlestick price chart with zoom, crosshair and time scale"><div ref={host} style={{height:480}}/><svg className="chart-drawing-layer" style={{pointerEvents:pro&&tool!=='cursor'?'auto':'none'}} onClick={draw} onPointerDown={e=>brush(e,true)} onPointerMove={e=>brush(e)} data-revision={revision} aria-label="Chart annotation layer">{projected.map(({drawing:d,points},i)=>{const a=points[0],b=points[1]??points[0];const color='#d49d52';if(d.tool==='brush')return <polyline key={i} points={points.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke={color} strokeWidth="3"/>;if(d.tool==='horizontal')return <line key={i} x1="0" x2="100%" y1={a.y} y2={a.y} stroke={color}/>;if(d.tool==='vertical')return <line key={i} x1={a.x} x2={a.x} y1="0" y2="100%" stroke={color}/>;if(d.tool==='rectangle')return <rect key={i} x={Math.min(a.x,b.x)} y={Math.min(a.y,b.y)} width={Math.abs(a.x-b.x)} height={Math.abs(a.y-b.y)} fill="#d49d5222" stroke={color}/>;if(d.tool==='fib')return <g key={i}>{[0,.236,.382,.5,.618,.786,1].map(r=><g key={r}><line x1={Math.min(a.x!,b.x!)} x2={Math.max(a.x!,b.x!)} y1={a.y!+(b.y!-a.y!)*r} y2={a.y!+(b.y!-a.y!)*r} stroke={color}/><text x={Math.min(a.x!,b.x!)} y={a.y!+(b.y!-a.y!)*r-3} fill={color}>{r}</text></g>)}</g>;if(d.tool==='text'||d.tool==='label')return <text key={i} x={a.x} y={a.y} fill={color}>{d.tool==='label'?money(d.points[0].price):d.text}</text>;return <g key={i}><line x1={a.x} x2={b.x} y1={a.y} y2={b.y} stroke={color} strokeWidth={2}/>{d.tool==='arrow'&&<path d={`M${b.x-7} ${b.y-5}L${b.x} ${b.y}L${b.x-7} ${b.y+5}`} fill="none" stroke={color} strokeWidth="2"/>}</g>;})}{wickPixels.map((p,i)=><line key={`wick-${i}`} x1={p.x} x2={p.x} y1={p.high} y2={p.low} stroke={p.color} strokeWidth={wick}/>)}</svg></div>
 {toolset.includes('VolumeProfile')&&<div className="chart-profile"><h4>Generated activity by close-price bucket</h4>{Array.from({length:8},(_,i)=>{const low=Math.min(...data.map(b=>b.low)),high=Math.max(...data.map(b=>b.high)),start=low+(high-low)*i/8,end=low+(high-low)*(i+1)/8,volume=data.filter(b=>b.close>=start&&b.close<end).reduce((s,b)=>s+b.volume,0);return <div key={i}><span>{money(start)}</span><meter min="0" max={data.reduce((s,b)=>s+b.volume,0)} value={volume}/><small>{volume}</small></div>;})}</div>}
 {toolset.includes('VolumeHeatmap')&&<div className="chart-volume-heat" aria-label="Generated activity heatmap">{data.slice(-40).map(b=><span key={b.time} title={`Generated activity ${b.volume}`} style={{opacity:.2+.8*b.volume/Math.max(...data.map(x=>x.volume)),background:bull}}/>)}</div>}
 {pro&&comparison&&<details><summary>Open second chart · {comparison}</summary><SimpleCandlestickChart data={chartBars(comparison,interval,replayTick??state.tick).slice(0,data.length).map((b,i)=>({...b,period:String(i+1)}))}/></details>}<p className="small">{state.holdings.find(h=>h.ticker===ticker)?`Position: ${state.holdings.find(h=>h.ticker===ticker)!.shares} units · average entry ${money(state.holdings.find(h=>h.ticker===ticker)!.averageCost)} · current virtual P/L ${money((full.at(-1)!.close-state.holdings.find(h=>h.ticker===ticker)!.averageCost)*state.holdings.find(h=>h.ticker===ticker)!.shares)}`:'No open position in this asset.'}</p>{alertNotice&&<p role="status">{alertNotice}</p>}<p className="small">Generated practice prices · {interval} candles · {replay===null?'Current simulated quote':`Replay: ${data.length} of ${full.length} bars`} · Drag or scroll to navigate. No real exchange volume, bid/ask or order book.</p><a href="https://www.tradingview.com/" target="_blank" rel="noopener noreferrer" className="small">Chart technology by TradingView Lightweight Charts</a>
 </div>;
}
