"use client";
import {useState} from 'react';
import Link from 'next/link';
import {BookOpen,CandlestickChart,Activity,ShieldCheck,Brain,ArrowRight} from 'lucide-react';
import type {State} from '@/types';
import {lessons} from '@/lib/education';
const modules=[{title:'Basics',icon:BookOpen,ids:[1,2,3,4,5]},{title:'Candlesticks',icon:CandlestickChart,ids:[26,27,28,29,30]},{title:'Indicators',icon:Activity,ids:[55,56,57,58,59]},{title:'Risk',icon:ShieldCheck,ids:lessons.filter(l=>l.level===8).map(l=>l.id)},{title:'Psychology',icon:Brain,ids:lessons.filter(l=>l.level===9).map(l=>l.id)}];
const series=[100,101,100.5,102,101.5,103,102.5,103.5,103,104,103.5,104.5,104,103.8,104.8,106,107,106,108,107,109,110,108.5,111];
export function MiniChart({values=series,highlight=false}:{values?:number[];highlight?:boolean}){
 const min=Math.min(...values)-1,max=Math.max(...values)+1;
 const points=values.map((v,i)=>`${20+i*360/Math.max(1,values.length-1)},${140-(v-min)/(max-min)*110}`).join(' ');
 return <svg className="mini-learning-chart" viewBox="0 0 400 160" role="img" aria-label={highlight?'Illustrative breakout chart with a highlighted resistance area':'Illustrative price chart'}><path d="M20 40H380M20 90H380M20 140H380" stroke="var(--line)" strokeDasharray="4 5" fill="none"/>{highlight&&<><rect className="pattern-glow" x="190" y="64" width="65" height="47" rx="14"/><path d="M20 92H380" stroke="var(--green)" strokeDasharray="5 5"/><text x="22" y="84" fill="var(--muted)" fontSize="11">Prior resistance</text></>}<polyline points={points} fill="none" stroke="var(--green)" strokeWidth="3" strokeLinejoin="round"/><circle cx="380" cy={140-(values.at(-1)!-min)/(max-min)*110} r="5" fill="var(--green)"/></svg>;
}
export function LearningRoadmap({state,onNavigate}:{state:State;onNavigate?:(url:string)=>void}){return <section className="visual-section" id="roadmap"><div className="section-intro"><span className="eyebrow">ONE SMALL STEP AT A TIME</span><h2>Your path from curious to capable</h2><p>Five starting points. Short lessons. Progress you can see.</p></div><div className="roadmap-grid">{modules.map((m,i)=>{const done=m.ids.filter(id=>state.learning.completed.includes(id)).length,next=m.ids.find(id=>!state.learning.completed.includes(id))??m.ids[0],url=`/learn?lesson=${next}`;return <article className="card roadmap-card" key={m.title}><span className="module-icon"><m.icon size={24}/></span><small>MODULE {i+1}</small><h3>{m.title}</h3><progress aria-label={`${m.title} module progress`} value={done} max={m.ids.length}/><span className="small">{done} / {m.ids.length} lessons complete</span>{onNavigate?<button className="text-link" onClick={()=>onNavigate(url)}>Continue {m.title} <ArrowRight size={15}/></button>:<Link className="text-link" href={url}>Continue {m.title} <ArrowRight size={15}/></Link>}</article>;})}</div></section>}
export function PatternPreview({onNavigate}:{onNavigate:(url:string)=>void}){const [step,setStep]=useState(15);return <section className="card homepage-pattern"><div><span className="eyebrow">SEE IT. UNDERSTAND IT. PRACTICE IT.</span><h2>What happens at a breakout?</h2><p>Move the slider to reveal this example’s next candles. Notice how price tests an old ceiling before moving beyond it.</p><button className="primary" onClick={()=>onNavigate('/practice?scenario=0#chart-practice')}>Learn This Pattern <ArrowRight size={17}/></button><p className="small">Illustrative scenario. Other breakouts fail; a pattern is never a promise.</p></div><div><MiniChart values={series.slice(0,step)} highlight/><label htmlFor="outcome-slider" className="slider-caption"><span>Before</span><strong>{step===15?'At the decision':`${step-15} periods later`}</strong><span>After →</span></label><input id="outcome-slider" aria-label="Before and after chart outcome" type="range" min="15" max="24" value={step} onChange={e=>setStep(Number(e.target.value))}/></div></section>}
export function StrategyCards({onNavigate}:{onNavigate?:(url:string)=>void}){return <section className="visual-section"><div className="section-intro"><span className="eyebrow">EXPLORE A SETUP BEFORE YOU TRY IT</span><h2>Strategies, made visual</h2><p>Study entries and invalidation. Passing on a trade is a valid choice.</p></div><div className="strategy-grid">{[{title:'Breakout & retest',level:'Intermediate',scenario:0,values:series},{title:'Support & resistance',level:'Beginner',scenario:1,values:[103,101,100,102,104,101,100,103,105]},{title:'Trend pullback',level:'Intermediate',scenario:2,values:[100,102,101,104,103,105,103,104,106]}].map(s=><article className="card strategy-card" key={s.title}><span className="badge">{s.level}</span><MiniChart values={s.values}/><h3>{s.title}</h3><p>Explore a worked example and plan what would make the idea fail.</p>{onNavigate?<button className="text-link" onClick={()=>onNavigate(`/practice?scenario=${s.scenario}#chart-practice`)}>Learn More: {s.title} <ArrowRight size={15}/></button>:<Link className="text-link" href={`/practice?scenario=${s.scenario}#chart-practice`}>Learn More: {s.title} <ArrowRight size={15}/></Link>}</article>)}</div></section>}
