"use client";
import {useState} from 'react';
import {ProGate,useSubscription} from "./Subscription";
import ToolGuide from './ToolGuide';
import {Calculator,ShieldCheck,TrendingUp,Gauge,Lock} from 'lucide-react';
import {positionSize,hypotheticalProfit,volatility} from '@/lib/trading/tools';
import {candles,money} from '@/lib/market';
export default function VisualTools({tick=0}:{tick?:number}){
 const {pro,upgrade}=useSubscription();
 if(pro)return <UnlockedTools tick={tick}/>;
 const previews=[{title:'Position size calculator',icon:Calculator,description:'Estimate how many shares fit your practice budget and planned loss limit.'},{title:'Risk calculator',icon:ShieldCheck,description:'Compare a planned risk percentage with the dollars you could lose.'},{title:'Profit / loss explorer',icon:TrendingUp,description:'Explore hypothetical gains and losses at different exit prices.'},{title:'Volatility meter',icon:Gauge,description:'Understand how much generated price movement varies before a practice trade.'}];
 return <section className="visual-section" id="tools"><div className="section-intro"><span className="eyebrow">4 FINANCIAL TOOLS · SPROUT PRO</span><h2>Explore your trading toolkit</h2><p>Preview each tool below. Sprout Pro unlocks the calculators, sliders, and interactive displays.</p></div><div className="tools-grid">{previews.map(tool=><article className="card visual-tool locked-tool" key={tool.title}><span className="module-icon"><tool.icon size={24}/></span><span className="pro-pill"><Lock size={13}/> Pro · Locked</span><h3>{tool.title}</h3><p>{tool.description}</p><div className="locked-tool-preview" aria-hidden="true"><tool.icon size={45}/><Lock size={20}/></div><button className="secondary full" onClick={()=>upgrade(tool.title)}><Lock size={15}/>Unlock with Pro</button></article>)}</div></section>;
}
function UnlockedTools({tick}:{tick:number}){
 const [balance,setBalance]=useState(1000),[risk,setRisk]=useState(1),[entry,setEntry]=useState(100),[stop,setStop]=useState(98),[exitPercent,setExitPercent]=useState(104);
 const exit=entry*exitPercent/100;
 const size=positionSize(balance,risk,entry,stop),profit=size?hypotheticalProfit(size.shares,entry,exit):0;
 const movement=volatility(candles('SPY','LIVE',tick).map(c=>c.close)),gauge=Math.min(100,movement/3*100);
 return <section className="visual-section" id="tools"><div className="section-intro"><span className="eyebrow">TURN NUMBERS INTO UNDERSTANDING</span><h2>Small tools. Clearer decisions.</h2><p>Explore a hypothetical long position. These inputs do not place a trade or change your account.</p></div><div className="tools-grid"><article className="card visual-tool"><span className="module-icon"><Calculator size={24}/></span><h3>Position size calculator</h3><ToolGuide description="Estimates how many shares fit your practice budget and planned loss limit for a buy trade." steps={['Enter your total practice budget, the price you would buy at (entry), and a lower price where you would plan to exit if wrong (stop).','Choose your risk percentage in the Risk calculator next to this tool. Both tools share these inputs.','Read the whole-share result. It respects both your risk limit and the cash available to buy shares.']} example="$1,000 budget, 1% risk, $100 entry, and $98 stop: $10 risk ÷ $2 per share = 5 shares."/><label>Practice budget ($)<input aria-label="Calculator practice budget" type="number" min="1" max="1000000" value={balance} onChange={e=>setBalance(Number(e.target.value))}/></label><label>Risk budget (%)<input aria-label="Position sizing risk percentage" type="number" min="0.1" max="10" step="0.1" value={risk} onChange={e=>setRisk(Number(e.target.value))}/></label><div className="calculator-prices"><label>Entry ($)<input aria-label="Calculator entry price" type="number" min="0.01" step="0.01" value={entry} onChange={e=>setEntry(Number(e.target.value))}/></label><label>Stop ($)<input aria-label="Calculator stop price" type="number" min="0.01" step="0.01" value={stop} onChange={e=>setStop(Number(e.target.value))}/></label></div><strong className="tool-number" aria-live="polite">{size?size.shares.toLocaleString():'—'} <small>shares</small></strong><p className="small">Whole shares, capped by the budget. A stop is a planning input here, not an executed order.</p>{!size&&<p role="alert">Use positive prices and a stop below the entry.</p>}</article>
 <ProGate feature="Risk calculator"><article className="card visual-tool"><span className="module-icon"><ShieldCheck size={24}/></span><h3>Risk calculator</h3><ToolGuide description="Shows the portion of your practice budget you plan to put at risk on one trade—not the amount you spend buying shares." steps={['Set your practice budget in the Position size calculator.','Move the risk slider to choose a percentage of that budget.','Read the dollar risk budget and planned size risk. Changing the slider also updates the share count and profit/loss explorer.']} example="1% of $1,000 is $10. Buying 5 shares at $100 costs $500, but the planned loss at a $98 stop is $10 before fees or slippage."/><div className="risk-donut" style={{background:`conic-gradient(var(--green) ${risk}%, var(--pale) 0)`}} role="img" aria-label={`${risk}% planned risk budget`}><span>{risk.toFixed(1)}%<small>risk budget</small></span></div><label htmlFor="risk-percent">Risk budget: {money(balance*risk/100)}</label><input id="risk-percent" aria-label="Risk percentage" type="range" min="0.5" max="10" step="0.5" value={risk} onChange={e=>setRisk(Number(e.target.value))}/><p className="small">Planned size risk: {size?money(size.plannedRisk):'—'}. Gaps, slippage, and fees can make actual losses larger.</p></article></ProGate>
 <ProGate feature="Profit / loss explorer"><article className="card visual-tool"><span className="module-icon"><TrendingUp size={24}/></span><h3>Profit / loss explorer</h3><ToolGuide description="Compares a hypothetical gain or loss at an exit price with the planned loss at your stop." steps={['Set your budget, entry, stop, and risk percentage in the first two tools.','Drag the exit slider to try selling between 80% and 120% of your entry price.','Compare At stop with At exit. Green means a gain; red means a loss. Read the dollar amounts as well as the bars.']} example="With 5 shares bought at $100, a $104 exit gives a $20 gain before fees. A $96 exit gives a $20 loss."/><label>Hypothetical exit: {money(exit)}<input aria-label="Hypothetical exit price" type="range" min="80" max="120" step="0.1" value={exitPercent} onChange={e=>setExitPercent(Number(e.target.value))}/></label><div className="profit-bars" role="img" aria-label={`Planned loss ${size?money(size.plannedRisk):'unavailable'}, hypothetical profit or loss ${money(profit)}`}><div><span className="negative">{size?money(-size.plannedRisk):'—'}</span><i className="loss-bar" style={{height:`${size?Math.max(8,Math.min(100,size.plannedRisk/Math.max(size.plannedRisk,Math.abs(profit),1)*100)):8}px`}}/><small>At stop</small></div><div><span className={profit>=0?'positive':'negative'}>{size?money(profit):'—'}</span><i className={profit>=0?'gain-bar':'loss-bar'} style={{height:`${Math.max(8,Math.min(100,Math.abs(profit)/Math.max(size?.plannedRisk??0,Math.abs(profit),1)*100))}px`}}/><small>At exit</small></div></div><p className="small">Shares × (exit − entry), before fees. Hypothetical results are not predictions.</p></article></ProGate>
 <article className="card visual-tool"><span className="module-icon"><Gauge size={24}/></span><h3>Volatility meter</h3><ToolGuide description="Shows how much generated SPY price changes vary. More variability means a less steady price—not a prediction of its direction." steps={['Read the percentage and gauge; no inputs are needed. It follows the simulator’s generated SPY candles.','A lower reading means recent percentage changes were more consistent; a higher reading means they varied more.','Use it to practice thinking about uncertainty and position size. It does not tell you when to buy or sell.']} example="A rising gauge shows greater variability in recent changes, even if the price trend stays the same."/><svg viewBox="0 0 200 120" role="img" aria-label={`Simulated SPY movement ${movement.toFixed(3)}% per 30-second close`}><path d="M20 100 A80 80 0 0 1 180 100" fill="none" stroke="var(--pale)" strokeWidth="18" strokeLinecap="round"/><path d="M20 100 A80 80 0 0 1 180 100" fill="none" stroke="var(--green)" strokeWidth="18" pathLength="100" strokeDasharray={`${gauge} 100`} strokeLinecap="round"/><path d="M100 100L100 33" stroke="var(--ink)" strokeWidth="3" transform={`rotate(${gauge*1.8-90} 100 100)`}/><circle cx="100" cy="100" r="7" fill="var(--ink)"/></svg><strong className="tool-number">{movement.toFixed(3)}%<small>30-second return variability</small></strong><p className="small">Generated SPY candles. Standard deviation of consecutive close returns; gauge scale 0–3%. No live exchange data.</p></article></div></section>
}
