"use client";
import {useState} from 'react';
import {Calculator,ShieldCheck,TrendingUp,Gauge} from 'lucide-react';
import {positionSize,hypotheticalProfit,volatility} from '@/lib/trading/tools';
import {candles,money} from '@/lib/market';
export default function VisualTools({tick=0}:{tick?:number}){
 const [balance,setBalance]=useState(1000),[risk,setRisk]=useState(1),[entry,setEntry]=useState(100),[stop,setStop]=useState(98),[exitPercent,setExitPercent]=useState(104);
 const exit=entry*exitPercent/100;
 const size=positionSize(balance,risk,entry,stop),profit=size?hypotheticalProfit(size.shares,entry,exit):0;
 const movement=volatility(candles('SPY','LIVE',tick).map(c=>c.close)),gauge=Math.min(100,movement/3*100);
 return <section className="visual-section" id="tools"><div className="section-intro"><span className="eyebrow">TURN NUMBERS INTO UNDERSTANDING</span><h2>Small tools. Clearer decisions.</h2><p>Explore a hypothetical long position. These inputs do not place a trade or change your account.</p></div><div className="tools-grid"><article className="card visual-tool"><span className="module-icon"><Calculator size={24}/></span><h3>Position size calculator</h3><label>Practice budget ($)<input aria-label="Calculator practice budget" type="number" min="1" max="1000000" value={balance} onChange={e=>setBalance(Number(e.target.value))}/></label><div className="calculator-prices"><label>Entry ($)<input aria-label="Calculator entry price" type="number" min="0.01" step="0.01" value={entry} onChange={e=>setEntry(Number(e.target.value))}/></label><label>Stop ($)<input aria-label="Calculator stop price" type="number" min="0.01" step="0.01" value={stop} onChange={e=>setStop(Number(e.target.value))}/></label></div><strong className="tool-number" aria-live="polite">{size?size.shares.toLocaleString():'—'} <small>shares</small></strong><p className="small">Whole shares, capped by the budget. A stop is a planning input here, not an executed order.</p>{!size&&<p role="alert">Use positive prices and a stop below the entry.</p>}</article>
 <article className="card visual-tool"><span className="module-icon"><ShieldCheck size={24}/></span><h3>Risk calculator</h3><div className="risk-donut" style={{background:`conic-gradient(var(--green) ${risk}%, var(--pale) 0)`}} role="img" aria-label={`${risk}% planned risk budget`}><span>{risk.toFixed(1)}%<small>risk budget</small></span></div><label htmlFor="risk-percent">Risk budget: {money(balance*risk/100)}</label><input id="risk-percent" aria-label="Risk percentage" type="range" min="0.5" max="10" step="0.5" value={risk} onChange={e=>setRisk(Number(e.target.value))}/><p className="small">Planned size risk: {size?money(size.plannedRisk):'—'}. Gaps, slippage, and fees can make actual losses larger.</p></article>
 <article className="card visual-tool"><span className="module-icon"><TrendingUp size={24}/></span><h3>Profit / loss explorer</h3><label>Hypothetical exit: {money(exit)}<input aria-label="Hypothetical exit price" type="range" min="80" max="120" step="0.1" value={exitPercent} onChange={e=>setExitPercent(Number(e.target.value))}/></label><div className="profit-bars" role="img" aria-label={`Planned loss ${size?money(size.plannedRisk):'unavailable'}, hypothetical profit or loss ${money(profit)}`}><div><span className="negative">{size?money(-size.plannedRisk):'—'}</span><i className="loss-bar" style={{height:`${size?Math.max(8,Math.min(100,size.plannedRisk/Math.max(size.plannedRisk,Math.abs(profit),1)*100)):8}px`}}/><small>At stop</small></div><div><span className={profit>=0?'positive':'negative'}>{size?money(profit):'—'}</span><i className={profit>=0?'gain-bar':'loss-bar'} style={{height:`${Math.max(8,Math.min(100,Math.abs(profit)/Math.max(size?.plannedRisk??0,Math.abs(profit),1)*100))}px`}}/><small>At exit</small></div></div><p className="small">Shares × (exit − entry), before fees. Hypothetical results are not predictions.</p></article>
 <article className="card visual-tool"><span className="module-icon"><Gauge size={24}/></span><h3>Volatility meter</h3><svg viewBox="0 0 200 120" role="img" aria-label={`Simulated SPY movement ${movement.toFixed(3)}% per 30-second close`}><path d="M20 100 A80 80 0 0 1 180 100" fill="none" stroke="var(--pale)" strokeWidth="18" strokeLinecap="round"/><path d="M20 100 A80 80 0 0 1 180 100" fill="none" stroke="var(--green)" strokeWidth="18" pathLength="100" strokeDasharray={`${gauge} 100`} strokeLinecap="round"/><path d="M100 100L100 33" stroke="var(--ink)" strokeWidth="3" transform={`rotate(${gauge*1.8-90} 100 100)`}/><circle cx="100" cy="100" r="7" fill="var(--ink)"/></svg><strong className="tool-number">{movement.toFixed(3)}%<small>30-second return variability</small></strong><p className="small">Generated SPY candles. Standard deviation of consecutive close returns; gauge scale 0–3%. No live exchange data.</p></article></div></section>
}
