import {lessons,levels} from '@/lib/education';
export interface HelpLink {label:string;href:string;}
export interface HelpAnswer {text:string;links:HelpLink[];}
interface Entry extends HelpAnswer {id:string;keywords:string;}
const faq:Entry[]=[
 {id:'start',keywords:'starting start beginner minimum money amount balance deposit budget affordable free cost learn now',text:'There is no single amount everyone needs to begin learning. Sprout starts you with $10,000 in virtual cash and does not require a real deposit. Start learning now, at your own pace. Actual brokers and products can have different minimums; using real money should follow your budget, essential savings, debt situation, and understanding of risk.',links:[{label:'Starting with the amount that fits you',href:'/learn?lesson=60'},{label:'Explore personal finance',href:'/learn#curriculum'}]},
 {id:'account',keywords:'account login sign in signup sign up register create first name save progress cloud email confirmation',text:'Open Account and enter your first name, email, and a password of at least eight characters, then choose Create account. If email confirmation is required, follow the link in your inbox and return to sign in. Signed-in accounts save learning and the practice portfolio across devices. Guest progress is saved in this browser.',links:[{label:'Open Account',href:'#account'}]},
 {id:'referrals',keywords:'referral referrals refer friend code bonus reward extra cash 10000 ten thousand',text:'Share the referral code shown on your dashboard or Profile. A new friend creates an account, confirms their email, and redeems the code within seven days of joining. You receive $10,000 in virtual practice cash per qualifying friend. Self-referrals and duplicate claims do not qualify. Refresh your bonus balance to see an award; deposits are excluded from trading profit.',links:[{label:'Open your referral code',href:'/profile#referrals'}]},
 {id:'virtual',keywords:'withdraw withdrawal withdrawl cash out real money actual fake profits deposit payment dollars simulation',text:'Sprout is an educational simulator. Its cash, trades, prices, and referral bonuses are virtual and have no cash value; they cannot be withdrawn. No real securities are traded. You can practice without depositing or risking real money.',links:[{label:'Open the simulator',href:'/market'}]},
 {id:'prices',keywords:'prices price live realtime real time feed data market hours 24/7 movement moving stocks ETFs search ticker',text:'Sprout generates approximate stock and ETF prices that update around the clock. They are not live exchange quotes, and the simulation does not follow real exchange hours. Use the market search to find an available US-listed stock or ETF. Its detail page includes line and candlestick charts, timeframes, and a virtual trade ticket.',links:[{label:'Search the stock and ETF catalog',href:'/market'},{label:'Understand trading hours',href:'/learn?lesson=32'}]},
 {id:'trade',keywords:'place order buy sell purchase shares stock trade ticket how simulator limit cash pending',text:'Open Simulator, search for a stock or ETF, and select it. In the trade ticket, choose Buy or Sell, enter a whole number of shares, review the virtual cost, and confirm. You can only sell shares you own. Market orders use the simulated quote; limit orders wait for their price condition and can be cancelled in Trade History.',links:[{label:'Practice your first trade',href:'/market/AAPL?guided=1'},{label:'Learn order placement',href:'/learn?lesson=34'}]},
 {id:'rewards',keywords:'reward rewards xp badge badges milestone achievement achievements modules lessons completion streak quiz pass score 80 percent presentation',text:'Read the interactive presentation, then take its quiz. You need at least 80% to pass; below that, review and retry before progressing or earning completion rewards. Your first passed completion of a lesson earns 35 XP. Completing a module adds 100 XP once, and the expanded modules each unlock a mastery badge. There are also milestones for 50 and 100 lessons and completing the current curriculum. Repeating an already-completed lesson does not earn its completion XP again. Rewards track learning, not professional certification or guaranteed trading skill.',links:[{label:'View your achievements',href:'/achievements'},{label:'Browse lessons',href:'/learn#curriculum'}]},
 {id:'theme',keywords:'dark light mode theme colors colour color readability night appearance',text:'Use the sun or moon button near the top of the page to switch between light and dark mode. Your choice is saved in this browser. Charts, cards, calculators, and Sprouty’s help panel follow the selected theme.',links:[]},
 {id:'journal',keywords:'journal review notes mood emotion emotions tilt analytics win rate average r performance best worst challenge goals',text:'Practice Lab includes replayable charts, the trade journal, performance statistics, and optional challenges. You can record a trade’s plan, emotion, and initial risk; average R needs that recorded risk. Tools includes a private mood check-in graph and visual calculators. A red Tilt Warning reflects your recent reported moods, not a diagnosis.',links:[{label:'Open Practice Lab',href:'/practice'},{label:'Open tools and mood tracker',href:'/tools'}]},
 {id:'support',keywords:'human person agent support contact complaint feedback customer service help bug problem issue broken',text:'I’m Sprouty, an automated guide available any time. I can explain Sprout features and point you to lessons, but I cannot access passwords, change account records, or connect you to a live agent. Community lets you share questions and feedback with other learners. Community posts are public, so keep account secrets and personal financial details out of them.',links:[{label:'Open Community',href:'/community'}]},
 {id:'recovery',keywords:'reset password forgot forgotten recovery cannot cant login log in password access',text:'If sign-in fails, check your email and password and whether you confirmed your email. Your guest workspace stays separate from your cloud account. Sprouty cannot see or recover a password. To report an account-access issue, use Community without sharing credentials. Signing out does not delete your cloud progress.',links:[{label:'Open Account',href:'#account'},{label:'Community questions',href:'/community'}]},
];
const stop=new Set('a an the and or to for of in on with is are was be i me my we you your it this that how what why can could do does did please tell explain about learn learning understand thanks'.split(' '));
export function helpTokens(text:string){return text.toLowerCase().replace(/401\s*\(\s*k\s*\)/g,'401k').replace(/\b(10|8)[-\s]*(k|q)\b/g,'$1$2').replace(/form([345])\b/g,'form $1').replace(/forms/g,'form').replace(/candlesticks/g,'candlestick').replace(/referrals/g,'referral').replace(/budgeting/g,'budget').replace(/investing/g,'invest').replace(/taxes/g,'tax').replace(/options/g,'option').replace(/stocks/g,'stock').replace(/etfs/g,'etf').replace(/bonds/g,'bond').replace(/trades/g,'trade').match(/[a-z0-9]+/g)?.filter(w=>(w.length>1||/^\d+$/.test(w))&&!stop.has(w))??[];}
const entries:Entry[]=[...faq,...lessons.map(l=>({id:`lesson-${l.id}`,keywords:`${l.title} ${l.title} ${levels[l.level-1]} ${l.explanation}`,text:l.explanation,links:[{label:l.title,href:`/learn?lesson=${l.id}`}]}))];
const documents=entries.map(e=>helpTokens(e.keywords)),frequency=new Map<string,number>();
for(const words of documents)for(const word of new Set(words))frequency.set(word,(frequency.get(word)??0)+1);
export function answerHelp(question:string,previousLesson?:number):HelpAnswer{
 const q=question.trim();
 if(previousLesson&&/^(?:can you |please )?(?:give (?:me )?an example|show (?:me )?an example|example|tell me more|explain more|why does (?:this|that) matter)[?.! ]*$/i.test(q)){const lesson=lessons.find(l=>l.id===previousLesson);if(lesson)return {text:`${lesson.example} ${lesson.why}`,links:[{label:lesson.title,href:`/learn?lesson=${lesson.id}`}]};}

 if(/^(hi|hello|hey|thanks|thank you)[!.\s]*$/i.test(q))return {text:'Hello. Let’s break this down together. Ask about using Sprout, a trading concept, or personal finance.',links:[]};
 if(/(?:should i (?:buy|sell|trade|invest)|which stock|guaranteed? (?:profit|return)|clean entry|good entry)/i.test(q))return {text:'I can help you examine a setup and its risk, but I cannot decide whether a particular trade is right for you or promise its outcome. Start with the entry condition, size, possible loss, and invalidation. A profitable result alone does not establish a good process.',links:[{label:'Build a pre-trade checklist',href:'/learn?lesson=137'},{label:'Use the position size calculator',href:'/tools'}]};
 if(/withdraw|cash\s*out|real\s*money|actual\s*money/i.test(q)&&!/minimum|how much|start|budget|emergency/i.test(q))return faq.find(e=>e.id==='virtual')!;
 if(/(?:latest|current|today|live).*(?:insider|form\s*4)|(?:insider|form\s*4).*(?:latest|current|today|live)/i.test(q))return {text:'Sprout teaches how to read public insider disclosures, but does not provide a current insider-transaction feed. Use SEC EDGAR to check the company, transaction date, codes, and footnotes. A disclosed purchase or sale is one research input, not a guaranteed price signal.',links:[{label:'Read Forms 3, 4, and 5',href:'/learn?lesson=149'},{label:'Explore public insider research',href:'/learn?lesson=148'}]};
 if(/refer(?:ral)?|friend.?s? code|bonus/i.test(q))return faq.find(e=>e.id==='referrals')!;
 if(/(?:minimum|how much|amount).*(?:start|need|money)|(?:start|begin).*(?:money|amount|balance)/i.test(q))return faq.find(e=>e.id==='start')!;
 if(/(?:how|where) (?:do|can|to|would).*(?:place|make|buy|sell|purchase)/i.test(q)&&/trade|order|stock|share|etf|simulator|ticket/i.test(q)&&!/option|future|forex|crypto|bond|short sell|insider|research|bullish|bearish/i.test(q))return faq.find(e=>e.id==='trade')!;
 const words=[...new Set(helpTokens(q))];
 if(!words.length)return {text:'What would you like to understand? Try asking about your account, virtual trades, budgeting, candlesticks, or lesson rewards.',links:[]};
 const scored=entries.map((e,i)=>{const tokens=documents[i];let matched=0,score=0;for(const w of words){const count=tokens.filter(t=>t===w).length;if(count){matched++;score+=(1+Math.log(count))*Math.log(1+(entries.length-(frequency.get(w)??0)+.5)/((frequency.get(w)??0)+.5));}}return {entry:e,score:score/Math.sqrt(Math.max(1,tokens.length/25)),matched};}).filter(e=>e.matched>0).sort((a,b)=>b.score-a.score);
 const best=scored[0];
 if(!best||best.score<1.4||best.matched/words.length<.3)return {text:'I don’t have a reliable answer for that in Sprout’s help library. Try naming the feature or concept you mean. You can also browse the lessons or ask the community. I won’t guess about an account issue or a financial outcome.',links:[{label:'Browse the lesson library',href:'/learn#curriculum'},{label:'Ask the community',href:'/community'}]};
 return {text:best.entry.text,links:best.entry.links};
}
