import {candles,marketEpoch} from '@/lib/market';
export interface Bar {time:number;open:number;high:number;low:number;close:number;volume:number;}
export const intervals={'30s':15,'1m':30,'5m':150,'15m':450,'1h':1800,'1d':43200};
export type Interval=keyof typeof intervals;
export function chartBars(ticker:string,interval:Interval,tick:number):Bar[]{const width=intervals[interval],current=Math.floor(tick/width)*width;return candles(ticker,interval,tick,200).map((c,i)=>({...c,time:(marketEpoch+(current-(199-i)*width)*2000)/1000,volume:Math.round(500+Math.abs(Math.sin((current-(199-i)*width)*.17))*2500+Math.abs(c.close-c.open)/c.open*10000)}));}
export const sma=(values:number[],period:number)=>(values.map((_,i)=>i+1<period?null:values.slice(i-period+1,i+1).reduce((a,b)=>a+b,0)/period));
export function ema(values:number[],period:number){const result:number[]=[];values.forEach((v,i)=>result.push(i?result[i-1]+2/(period+1)*(v-result[i-1]):v));return result;}
function wilder(values:number[],period:number){const out:number[]=[];values.forEach((v,i)=>out.push(i?out[i-1]+(v-out[i-1])/period:v));return out;}
export function indicators(bars:Bar[],period=20){const c=bars.map(b=>b.close),typical=bars.map(b=>(b.high+b.low+b.close)/3),volume=bars.map(b=>b.volume),mean=sma(c,period),atr=wilder(bars.map((b,i)=>i?Math.max(b.high-b.low,Math.abs(b.high-c[i-1]),Math.abs(b.low-c[i-1])):b.high-b.low),14);
 const gains=wilder(c.map((v,i)=>i?Math.max(v-c[i-1],0):0),14),losses=wilder(c.map((v,i)=>i?Math.max(c[i-1]-v,0):0),14),rsi=c.map((_,i)=>i<14?null:losses[i]===0?(gains[i]===0?50:100):100-100/(1+gains[i]/losses[i]));
 const fast=ema(c,12),slow=ema(c,26),macd=c.map((_,i)=>fast[i]-slow[i]),signal=ema(macd,9);
 const deviation=c.map((_,i)=>mean[i]===null?null:Math.sqrt(c.slice(i-period+1,i+1).reduce((s,v)=>s+(v-mean[i]!)**2,0)/period));
 let amount=0,value=0,day=-1;const vwap=bars.map(b=>{const next=Math.floor(b.time/86400);if(next!==day){day=next;amount=0;value=0;}amount+=b.volume;value+=(b.high+b.low+b.close)/3*b.volume;return value/amount;});
 const stochastic=c.map((v,i)=>{if(i<13)return null;const recent=bars.slice(i-13,i+1),hi=Math.max(...recent.map(b=>b.high)),lo=Math.min(...recent.map(b=>b.low));return hi===lo?50:100*(v-lo)/(hi-lo);});
 const cci=typical.map((v,i)=>{if(i<period-1)return null;const values=typical.slice(i-period+1,i+1),average=values.reduce((a,b)=>a+b,0)/period,deviation=values.reduce((a,b)=>a+Math.abs(b-average),0)/period;return deviation? (v-average)/(.015*deviation):0;});
 let upper=0,lower=0,up=true;const supertrend=bars.map((b,i)=>{const midpoint=(b.high+b.low)/2,basicUpper=midpoint+3*atr[i],basicLower=midpoint-3*atr[i];if(!i){upper=basicUpper;lower=basicLower;}else{upper=basicUpper<upper||c[i-1]>upper?basicUpper:upper;lower=basicLower>lower||c[i-1]<lower?basicLower:lower;if(up&&b.close<lower)up=false;else if(!up&&b.close>upper)up=true;}return up?lower:upper;});
 return {SMA:mean,EMA:ema(c,period),VWAP:vwap,RSI:rsi,MACD:macd,Signal:signal,Histogram:macd.map((v,i)=>v-signal[i]),Stochastic:stochastic,CCI:cci,ATR:atr,Supertrend:supertrend,BollingerUpper:mean.map((m,i)=>m===null?null:m+2*deviation[i]!),BollingerLower:mean.map((m,i)=>m===null?null:m-2*deviation[i]!),VolumeMA:sma(volume,20)};
}
export function heikinAshi(bars:Bar[]):Bar[]{const out:Bar[]=[];bars.forEach((b,i)=>{const close=(b.open+b.high+b.low+b.close)/4,open=i?(out[i-1].open+out[i-1].close)/2:(b.open+b.close)/2;out.push({...b,open,close,high:Math.max(b.high,open,close),low:Math.min(b.low,open,close)});});return out;}
export function patternTags(bars:Bar[]){const tags:{index:number;label:string}[]=[];bars.forEach((b,i)=>{const range=b.high-b.low,body=Math.abs(b.close-b.open),top=b.high-Math.max(b.open,b.close),bottom=Math.min(b.open,b.close)-b.low,p=bars[i-1],p2=bars[i-2];if(!range)return;
 if(body<=range*.1)tags.push({index:i,label:'Doji'});else if(bottom>=body*2&&top<=body*.5)tags.push({index:i,label:'Hammer shape'});else if(top>=body*2&&bottom<=body*.5)tags.push({index:i,label:'Shooting-star shape'});
 if(p){if(b.high<p.high&&b.low>p.low)tags.push({index:i,label:'Inside bar'});if(b.close>b.open&&p.close<p.open&&b.open<=p.close&&b.close>=p.open)tags.push({index:i,label:'Bullish engulfing'});if(b.close<b.open&&p.close>p.open&&b.open>=p.close&&b.close<=p.open)tags.push({index:i,label:'Bearish engulfing'});}
 if(p&&p2){if(p2.close<p2.open&&Math.abs(p.close-p.open)<(p.high-p.low)*.3&&b.close>b.open&&b.close>(p2.open+p2.close)/2)tags.push({index:i,label:'Morning star candidate'});if(p2.close>p2.open&&Math.abs(p.close-p.open)<(p.high-p.low)*.3&&b.close<b.open&&b.close<(p2.open+p2.close)/2)tags.push({index:i,label:'Evening star candidate'});if([p2,p,b].every(x=>x.close>x.open)&&p.close>p2.close&&b.close>p.close)tags.push({index:i,label:'Three white soldiers candidate'});if([p2,p,b].every(x=>x.close<x.open)&&p.close<p2.close&&b.close<p.close)tags.push({index:i,label:'Three black crows candidate'});}});return tags;}
export function riskPlan(entry:number,stop:number,target:number,size:number){if(![entry,stop,target,size].every(v=>Number.isFinite(v)&&v>0)||entry===stop)return null;const direction=stop<entry?'long':'short';if(direction==='long'?target<=entry:target>=entry)return null;const risk=Math.abs(entry-stop)*size,reward=Math.abs(target-entry)*size;return {risk,reward,ratio:reward/risk,direction};}
